class CfgPatches {
    class CFP_O_IQARMY {
        units[] = {
            "CFP_O_IQARMY_Rifleman_01",
            "CFP_O_IQARMY_Squad_Leader_01",
            "CFP_O_IQARMY_Grenadier_01",
            "CFP_O_IQARMY_Machine_Gunner_01",
            "CFP_O_IQARMY_Auto_Rifleman_01",
            "CFP_O_IQARMY_Asst_Machine_Gunner_01",
            "CFP_O_IQARMY_Sniper_01",
            "CFP_O_IQARMY_Rifleman_AT_01",
            "CFP_O_IQARMY_AA_Specialist_01",
            "CFP_O_IQARMY_Medic_01",
            "CFP_O_IQARMY_Explosive_Specialist_01",
            "CFP_O_IQARMY_RG_Rifleman_01",
            "CFP_O_IQARMY_RG_Team_Leader_01",
            "CFP_O_IQARMY_RG_Grenadier_01",
            "CFP_O_IQARMY_RG_Machine_Gunner_01",
            "CFP_O_IQARMY_RG_Auto_Rifleman_01",
            "CFP_O_IQARMY_RG_Asst_Machine_Gunner_01",
            "CFP_O_IQARMY_RG_Sniper_01",
            "CFP_O_IQARMY_RG_Rifleman_AT_01",
            "CFP_O_IQARMY_RG_AA_Specialist_01",
            "CFP_O_IQARMY_RG_Medic_01",
            "CFP_O_IQARMY_RG_Explosive_Specialist_01",
            "CFP_O_IQARMY_Officer_01",
            "CFP_O_IQARMY_Crewman_01",
            "CFP_O_IQARMY_Helicopter_Pilot_01",
            "CFP_O_IQARMY_BRDM_2_01",
            "CFP_O_IQARMY_BTR_60PB_01",
            "CFP_O_IQARMY_BMP_2_01",
            "CFP_O_IQARMY_BMP_1_01",
            "CFP_O_IQARMY_MT_LB_01",
            "CFP_O_IQARMY_ZSU_23_4_01",
            "CFP_O_IQARMY_T72_01",
            "CFP_O_IQARMY_T55_01",
            "CFP_O_IQARMY_Ural_01",
            "CFP_O_IQARMY_Ural_Open_01",
            "CFP_O_IQARMY_Ural_Refuel_01",
            "CFP_O_IQARMY_Ural_Repair_01",
            "CFP_O_IQARMY_Ural_Ammo_01",
            "CFP_O_IQARMY_UAZ_01",
            "CFP_O_IQARMY_UAZ_Open_01",
            "CFP_O_IQARMY_UAZ_DShKM_01",
            "CFP_O_IQARMY_UAZ_AGS_30_01",
            "CFP_O_IQARMY_UAZ_SPG_01",
            "CFP_O_IQARMY_UAZ_Metis_01",
            "CFP_O_IQARMY_Mi_24D_01",
            "CFP_O_IQARMY_Mi_8MT_01",
            "CFP_O_IQARMY_Su_25_Frogfoot_01",
            "CFP_O_IQARMY_Ural_ZU_23_01",
            "CFP_O_IQARMY_BM_21_01",
            "CFP_O_IQARMY_DShKM_01",
            "CFP_O_IQARMY_DShKM_Minitripod_01",
            "CFP_O_IQARMY_AGS_30_01",
            "CFP_O_IQARMY_SPG_9_01",
            "CFP_O_IQARMY_Podnos_2B14_01",
            "CFP_O_IQARMY_D30_01",
            "CFP_O_IQARMY_ZU_23_01",
            "CFP_O_IQARMY_Igla_AA_Pod_01",
            "CFP_O_IQARMY_Pilot_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "cfp_uniforms",
            "CUP_WheeledVehicles_BRDM2",
            "CUP_WheeledVehicles_BTR60",
            "CUP_TrackedVehicles_BMP",
            "CUP_TrackedVehicles_MTLB",
            "CUP_TrackedVehicles_ZSU23",
            "CUP_TrackedVehicles_T72",
            "CUP_TrackedVehicles_T55",
            "CUP_WheeledVehicles_Ural",
            "CUP_WheeledVehicles_UAZ",
            "CUP_AirVehicles_Mi24",
            "CUP_AirVehicles_Mi8",
            "CUP_AirVehicles_Su25",
            "CUP_Weapons_StaticWeapons"
        };
        author = "CFP";
        authors[] = {"CFP"};
    };
};
