class CfgPatches {
    class CFP_I_WAGNER_WDL {
        units[] = {
            "CFP_I_WAGNER_Contractor_2_WDL_01",
            "CFP_I_WAGNER_Contractor_1_WDL_01",
            "CFP_I_WAGNER_Marksman_WDL_01",
            "CFP_I_WAGNER_Field_Medic_WDL_01",
            "CFP_I_WAGNER_Field_Specialist_RPK_WDL_01",
            "CFP_I_WAGNER_Field_Specialist_PKM_WDL_01",
            "CFP_I_WAGNER_Field_Specialist_RPG_18_WDL_01",
            "CFP_I_WAGNER_Field_Technician_WDL_01",
            "CFP_I_WAGNER_Bodyguard_1_WDL_01",
            "CFP_I_WAGNER_Bodyguard_2_WDL_01",
            "CFP_I_WAGNER_Security_Contractor_AKMN_WDL_01",
            "CFP_I_WAGNER_Security_Contractor_AK74_GL_WDL_01",
            "CFP_I_WAGNER_Security_Contractor_SVD_WDL_01",
            "CFP_I_WAGNER_Tactical_Driver_WDL_01",
            "CFP_I_WAGNER_Tactical_Pilot_WDL_01",
            "CFP_I_WAGNER_Tactical_Specialist_Igla_WDL_01",
            "CFP_I_WAGNER_Team_Coordinator_WDL_01",
            "CFP_I_WAGNER_BTR_80_WDL_01",
            "CFP_I_WAGNER_BMP_2_WDL_01",
            "CFP_I_WAGNER_Assault_Boat_WDL_01",
            "CFP_I_WAGNER_Quad_Bike_WDL_01",
            "CFP_I_WAGNER_Mk2_Light_Strike_Vehicle_WDL_01",
            "CFP_I_WAGNER_Ural_WDL_01",
            "CFP_I_WAGNER_Ural_Refuel_WDL_01",
            "CFP_I_WAGNER_Ural_Repair_WDL_01",
            "CFP_I_WAGNER_Ural_Ammo_WDL_01",
            "CFP_I_WAGNER_UAZ_Medevac_WDL_01",
            "CFP_I_WAGNER_UAZ_Open_WDL_01",
            "CFP_I_WAGNER_UAZ_WDL_01",
            "CFP_I_WAGNER_Van_Transport_WDL_01",
            "CFP_I_WAGNER_Hilux_WDL_01",
            "CFP_I_WAGNER_Hilux_DShKM_WDL_01",
            "CFP_I_WAGNER_Hilux_SPG_WDL_01",
            "CFP_I_WAGNER_Hilux_Igla_WDL_01",
            "CFP_I_WAGNER_Hilux_Metis_WDL_01",
            "CFP_I_WAGNER_MT_LB_LV_WDL_01",
            "CFP_I_WAGNER_Pchela_1T_WDL_01",
            "CFP_I_WAGNER_Mi24_D_WDL_01",
            "CFP_I_WAGNER_Mi8_WDL_01",
            "CFP_I_WAGNER_Ka60_WDL_01",
            "CFP_I_WAGNER_ZU_23_WDL_01",
            "CFP_I_WAGNER_SPG_9_WDL_01",
            "CFP_I_WAGNER_Mortar_WDL_01",
            "CFP_I_WAGNER_DShKM_WDL_01",
            "CFP_I_WAGNER_DShKM_Low_WDL_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "CUP_Creatures_Military_Russia",
            "A3_Characters_F",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USArmy",
            "CUP_Creatures_Military_USMC",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator"
        };
        author = "Drew";
        authors[] = {"Drew"};
    };
};
