#include "script_component.hpp"

class CfgPatches
{
    class ADDON
    {
        units[] = {};
		weapons[] = {
			"SP_AssaultMolle1_Black",
			"SP_AssaultMolle1_Green",
			"SP_AssaultMolle1_Tan",
			"SP_Bandolier1_Black",
			"SP_Bandolier1_Green",
			"SP_Bandolier1_Tan",
			"SP_Bandolier1_Grey",
			"SP_BluforMolle1_Black",
			"SP_BluforMolle1_Green",
			"SP_BluforMolle1_Tan",
			"SP_BluforMolle1_Grey",
			"SP_BluforMolle1_Un",
			"SP_ChestRig1_Black",
			"SP_ChestRig1_Green",
			"SP_ChestRig1_Tan",
			"SP_ChestRig1_Grey",
			"SP_FlyyeMolle1_Black",
			"SP_FlyyeMolle1_Green",
			"SP_FlyyeMolle1_Tan",
			"SP_FlyyeMolle1_Grey",
			"SP_Harness1_Black",
			"SP_Harness1_Green",
			"SP_Harness1_Tan",
			"SP_Harness1_Grey",
			"SP_Holster1_Black",
			"SP_Holster1_Brown",
			"SP_JackEllis1_Black",
			"SP_JackEllis1_Green",
			"SP_JackEllis1_Tan",
			"SP_JackEllis1_Grey",
			"SP_JackEllis1_White",
			"SP_JackEllis1_Blue",
			"SP_JackEllis1_UNBlue1",
			"SP_JackEllis1_PressBlue1",
			"SP_JackEllis1_PoliceBlack1",
			"SP_JackEllis1_SwatBlack1",
			"SP_JackEllis1_FBIBlack1",
			"SP_Modular1_Black",
			"SP_Modular1_Green",
			"SP_Modular1_Tan",
			"SP_Modular1_Grey",
			"SP_Modular1_White",
			"CFP_Modular1_M81",
			"CFP_Modular1_IranDPM",
			"CFP_Modular1_Woodland",
			"Modular1_Atacs_au",
			"SP_Modular2_Black",
			"SP_Modular2_Green",
			"SP_Modular2_Tan",
			"SP_Modular2_Grey",
			"SP_Modular2_White",
			"SP_OpforMolle1_Black",
			"SP_OpforMolle1_Green",
			"SP_OpforMolle1_Tan",
			"SP_OpforMolle1_Grey",
			"SP_OpforMolle1_Un",
			"SP_OpforRig1_Black",
			"SP_OpforRig1_Green",
			"SP_OpforRig1_Tan",
			"SP_OpforRig1_Grey",
			"CFP_Osprey1_Wd",
			"SP_PlateCarrier1_Black",
			"SP_PlateCarrier1_Green",
			"SP_PlateCarrier1_Tan",
			"SP_PlateCarrier1_Grey",
			"SP_PlateCarrier1_Hunter",
			"SP_PlateCarrier1_Hunter2",
			"SP_PlateCarrier1_ATacsFG",
			"PlateCarrier1_ATacsAU",
			"SP_PlateCarrier1_NodUrban",
			"SP_Tactical1_Black",
			"SP_Tactical1_Blue",
			"SP_Tactical1_Green",
			"SP_Tactical1_Tan",
			"SP_Tactical1_Grey",
			"SP_Tactical1_White",
			"CFP_Tactical1_IranDesert",
			"CFP_Tactical1_IranDesert2",
			"CFP_Tactical1_M81",
			"CFP_Tactical1_Marpat",
			"CFP_Tactical1_ACRDesert",
			"CFP_Tactical1_Woodland",
			"CFP_Tactical1_EDRL",
			"CFP_Tactical1_Flecktarn",
			"CFP_AK_VEST",
			"CFP_AK_VEST_Black",
			"CFP_AK_VEST_EDRL",
			"CFP_AK_VEST_LOlive",
			"CFP_AK_VEST_Olive",
			"CFP_AK_VEST_Tan",
			"CFP_AK_VEST_Flora_Arid",
			"CFP_AK_VEST_Lime",
			"CFP_Smersh_Tropic",
			"CFP_Smersh_ArmyGreen",
			"CFP_Smersh_Brown",
			"CFP_Smersh_Tan",
			"CFP_Smersh_Green",
			"CFP_Smersh_Creme",
			"CFP_Smersh_Olive",
			"CFP_UtilityJacket_Woodland",
			"CFP_UtilityJacket_PolygonWoodland",
			"CFP_UtilityJacket_PolygonDesert",
			"CFP_UtilityJacket_M81",
			"CFP_UtilityJacket_EDRL",
			"CFP_UtilityJacket_ChocChip",
			"CFP_TakJacket_Woodland",
			"CFP_TakJacket_PolygonWoodland",
			"CFP_TakJacket_PolygonDesert",
			"CFP_TakJacket_Marpat",
			"CFP_TakJacket_M81",
			"CFP_TakJacket_EDRL",
			"CFP_TakJacket_ChocChip"
		};
        author = MODULE_AUTHOR;
        authors[] = {"SP Craig", "Tupolov", "AuburnAlumni"};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"CFP_main","CFP_Models"};
        VERSION_CONFIG;
    };
};

#include "CfgWeapons.hpp"

