//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 176.143187 on Stable branch
// Generated with ALiVE version 1.5.0.1711091
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class CFP_O_SO_REBEL {
            name = "Somali Rebels";

            class Infantry {
                name = "Infantry";

                class o_so_rebel_infantry_rebel_squad_1 {
                    name = "Rebel Squad 1";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Warlord_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Sharpshooter_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Autorifleman_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Bonesetter_01";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AT_01";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AA_01";
                    };
                    class Unit8 {
                        position[] = { -20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_Light_01";
                    };
                    class Unit9 {
                        position[] = { 25 , -25 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_2_01";
                    };
                };

                class o_so_rebel_infantry_rebel_squad_2 {
                    name = "Rebel Squad 2";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Warlord_2_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_2_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_3_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Marksman_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Autorifleman_2_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AT_2_01";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Bonesetter_2_01";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Grenadier_2_01";
                    };
                    class Unit8 {
                        position[] = { -20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AA_2_01";
                    };
                    class Unit9 {
                        position[] = { 25 , -25 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_Light_01";
                    };
                };

                class o_so_rebel_infantry_rebel_fireteam_1 {
                    name = "Rebel Fireteam 1";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Autorifleman_2_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AT_2_01";
                    };
                };

                class o_so_rebel_infantry_rebel_fireteam_2 {
                    name = "Rebel Fireteam 2";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_2_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Grenadier_2_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AT_01";
                    };
                };

                class o_so_rebel_infantry_demo_team {
                    name = "Demo Team";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Bombmaker_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Bombmaker_2_01";
                    };
                };

                class o_so_rebel_infantry_dshkm_team_high {
                    name = "DShKM Team [High]";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Gunner_DShKM_High_01";
                    };
                };

                class o_so_rebel_infantry_dshkm_team_low {
                    name = "DShKM Team [Low]";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_2_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Gunner_DShKM_Low_01";
                    };
                };

                class o_so_rebel_infantry_spg_9team {
                    name = "SPG-9 Team";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_3_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Gunner_SPG_01";
                    };
                };

                class o_so_rebel_infantry_mortar_team {
                    name = "Mortar Team";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Warlord_2_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Gunner_Mortar_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class o_so_rebel_motorized_pk_technical {
                    name = "PK Technical";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Technical_PK_01";
                    };
                };

                class o_so_rebel_motorized_dshkm_technical {
                    name = "DShKM Technical";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Technical_DSHkM_01";
                    };
                };

                class o_so_rebel_motorized_spg_technical {
                    name = "SPG Technical ";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Technical_SPG_01";
                    };
                };

                class o_so_rebel_motorized_truck_squad {
                    name = "Truck squad";
                    side = 0;
                    faction = "CFP_O_SO_REBEL";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = { 0 , 0 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Truck_01";
                    };
                    class Unit1 {
                        position[] = { 5 , -5 , 0 };
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Warlord_01";
                    };
                    class Unit2 {
                        position[] = { -5 , -5 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = { 10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_Light_01";
                    };
                    class Unit4 {
                        position[] = { -10 , -10 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_2_01";
                    };
                    class Unit5 {
                        position[] = { 15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AT_01";
                    };
                    class Unit6 {
                        position[] = { -15 , -15 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Rifleman_AA_01";
                    };
                    class Unit7 {
                        position[] = { 20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Grenadier_01";
                    };
                    class Unit8 {
                        position[] = { -20 , -20 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Autorifleman_01";
                    };
                    class Unit9 {
                        position[] = { 25 , -25 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Bonesetter_01";
                    };
                    class Unit10 {
                        position[] = { -25 , -25 , 0 };
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_SO_REBEL_Marksman_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };

            class UInfantry {
                name = "Guard Infantry";

            };


        };

    };
};