//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 188.145285 on Stable branch
// Generated with ALiVE version 1.8.3.1812041
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class WEST {

        class CFP_B_CDF_SNW {
            name = "Chernarus Defense Forces [Winter]";

            class Infantry {
                name = "Infantry";

                class cfp_b_cdf_infantry_snw_infantry_squad_snw {
                    name = "Infantry Squad";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.6;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Grenadier_SNW_04";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Rifleman_SNW_04";
                    };
                    class Unit5 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit6 {
                        position[] = {13,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Grenadier_SNW_04";
                    };
                    class Unit7 {
                        position[] = {15,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit8 {
                        position[] = {17,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Rifleman_SNW_04";
                    };
                    class Unit9 {
                        position[] = {19,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Medic_SNW_04";
                    };
                };

                class cfp_b_cdf_infantry_snw_weapons_squad_snw {
                    name = "Weapons Squad";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.6;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Automatic_Rifleman_SNW_04";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit4 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit5 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit6 {
                        position[] = {13,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Grenadier_SNW_04";
                    };
                    class Unit7 {
                        position[] = {15,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Marksman_SNW_04";
                    };
                };

                class cfp_b_cdf_infantry_snw_infantry_section_at_snw {
                    name = "Infantry Section (AT)";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Automatic_Rifleman_SNW_04";
                    };
                };

                class cfp_b_cdf_infantry_snw_infantry_section_aa_snw {
                    name = "Infantry Section (AA)";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AA_Specialist_SNW_04";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AA_Specialist_SNW_04";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                };

                class cfp_b_cdf_infantry_snw_infantry_section_mg_snw {
                    name = "Infantry Section (MG)";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Automatic_Rifleman_SNW_04";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                };

                class cfp_b_cdf_infantry_snw_patrol_snw {
                    name = "Patrol";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Militia_SNW_04";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Militia_SNW_04";
                    };
                    class Unit2 {
                        position[] = {5,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Militia_SNW_04";
                    };
                    class Unit3 {
                        position[] = {7,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Militia_SNW_04";
                    };
                };

                class cfp_b_cdf_infantry_snw_sniper_team_snw {
                    name = "Sniper Team";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.05;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Sniper_SNW_04";
                    };
                    class Unit1 {
                        position[] = {3,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Sniper_SNW_04";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class cfp_b_cdf_motorized_motorized_infantry_squad_snw {
                    name = "Motorized Infantry Squad";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.4;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Ural_SNW_01";
                    };
                    class Unit2 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit3 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit4 {
                        position[] = {7,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Grenadier_SNW_04";
                    };
                    class Unit5 {
                        position[] = {9,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Rifleman_SNW_04";
                    };
                    class Unit6 {
                        position[] = {11,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit7 {
                        position[] = {13,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Grenadier_SNW_04";
                    };
                    class Unit8 {
                        position[] = {15,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                    class Unit9 {
                        position[] = {17,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Rifleman_SNW_04";
                    };
                    class Unit10 {
                        position[] = {19,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Medic_SNW_04";
                    };
                };

                class cfp_b_cdf_motorized_motorized_infantry_patrol_snw {
                    name = "Motorized Infantry Patrol";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.15;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Grenadier_SNW_04";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_UAZ_SNW_01";
                    };
                    class Unit2 {
                        position[] = {3,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                };

                class cfp_b_cdf_motorized_motorized_weapon_squad_snw {
                    name = "Motorized Weapon Squad";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.2;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_UAZ_AGS_30_SNW_01";
                    };
                    class Unit2 {
                        position[] = {-5,-7,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_UAZ_AGS_30_SNW_01";
                    };
                    class Unit3 {
                        position[] = {3,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class cfp_b_cdf_mechanized_mechanized_recon_section_snw {
                    name = "Mechanized Recon Section";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_BRDM_2_SNW_01";
                    };
                    class Unit2 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit3 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                };

                class cfp_b_cdf_mechanized_mechanized_recon_section_at_snw {
                    name = "Mechanized Recon Section (AT)";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,5,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Team_Leader_SNW_04";
                    };
                    class Unit1 {
                        position[] = {-5,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_BRDM_2ATGM_SNW_01";
                    };
                    class Unit2 {
                        position[] = {3,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Machinegunner_SNW_04";
                    };
                    class Unit3 {
                        position[] = {5,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "CFP_B_CDF_AT_Specialist_SNW_04";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class cfp_b_cdf_armored_tank_platoon_snw {
                    name = "Tank Platoon";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.25;

                    class Unit0 {
                        position[] = {0,10,0};
                        rank = "CAPTAIN";
                        side = 1;
                        vehicle = "CFP_B_CDF_T72_SNW_01";
                    };
                    class Unit1 {
                        position[] = {5,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_T72_SNW_01";
                    };
                    class Unit2 {
                        position[] = {10,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_T72_SNW_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class cfp_b_cdf_air_mi_24d_squadron_snw {
                    name = "Mi-24D Squadron";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.1;

                    class Unit0 {
                        position[] = {0,15,0};
                        rank = "CAPTAIN";
                        side = 1;
                        vehicle = "CFP_B_CDF_Mi_24D_SNW_01";
                    };
                    class Unit1 {
                        position[] = {15,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Mi_24D_SNW_01";
                    };
                };

                class cfp_b_cdf_air_mi_8squadron_snw {
                    name = "Mi-8 Squadron";
                    side = 1;
                    faction = "CFP_B_CDF_SNW";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,15,0};
                        rank = "CAPTAIN";
                        side = 1;
                        vehicle = "CFP_B_CDF_Mi_8MT_SNW_01";
                    };
                    class Unit1 {
                        position[] = {15,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "CFP_B_CDF_Mi_8MT_SNW_01";
                    };
                };

            };

            class Infantry_MNT {
                name = "Infantry (Mountain)";

            };

            class Infantry_DST {
                name = "Infantry (Desert)";

            };

            class Infantry_FST {
                name = "Infantry (Forest)";

            };

            class Infantry_SNW {
                name = "Infantry (Winter)";

            };


        };

    };
};