//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 198.146373 on Stable branch
// Generated with ALiVE version 1.3.7.0000000
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class CFP_O_HEZBOLLAH {
            name = "Hezbollah";

            class Infantry {
                name = "Infantry";

                class cfp_o_hezbollah_infantry_squad_paramilitary {
                    name = "Squad [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Explosive_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_infantry_fire_team_paramilitary {
                    name = "Fire Team [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Machine_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_infantry_at_team_paramilitary {
                    name = "AT Team [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                };

                class cfp_o_hezbollah_infantry_squad_militia {
                    name = "Squad [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Explosive_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_infantry_fire_team_militia {
                    name = "Fire Team [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Machine_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_infantry_at_team_militia {
                    name = "AT Team [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

                class cfp_o_hezbollah_specops_squad {
                    name = "Squad";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Squad_Leader_SF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_AT_SF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Medic_SF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Explosive_Specialist_SF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Machine_Gunner_SF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_SF_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_SF_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Grenadier_SF_01";
                    };
                };

                class cfp_o_hezbollah_specops_fire_team {
                    name = "Fire Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Squad_Leader_SF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_SF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Machine_Gunner_SF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Grenadier_SF_01";
                    };
                };

                class cfp_o_hezbollah_specops_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Sniper_SF_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Sniper_SF_01";
                    };
                };

                class cfp_o_hezbollah_specops_motorized_fire_team {
                    name = "Motorized Fire Team ";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Squad_Leader_SF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_SF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Machine_Gunner_SF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Grenadier_SF_01";
                    };
                };

                class cfp_o_hezbollah_specops_motorized_squad {
                    name = "Motorized Squad";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Truck_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Squad_Leader_SF_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_AT_SF_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Medic_SF_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Explosive_Specialist_SF_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Machine_Gunner_SF_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Grenadier_SF_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_SF_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Rifleman_SF_01";
                    };
                };

                class cfp_o_hezbollah_infantry_demo_team_paramilitary {
                    name = "Demo Team [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Explosive_Specialist_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Explosive_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_infantry_demo_team_militia {
                    name = "Demo Team [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Explosive_Specialist_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Explosive_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_infantry_dshkm_team {
                    name = "DShKM Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Asst_Gunner_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Gunner_DShKM_01";
                    };
                };

                class cfp_o_hezbollah_infantry_dshkm_low_team {
                    name = "DShKM [Low] Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                };

                class cfp_o_hezbollah_infantry_tow_at_team {
                    name = "TOW AT Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Asst_Gunner_TOW_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Gunner_TOW_01";
                    };
                };

                class cfp_o_hezbollah_infantry_metis_at_team {
                    name = "Metis AT Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Asst_Gunner_Metis_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Gunner_Metis_01";
                    };
                };

                class cfp_o_hezbollah_infantry_spg_9team {
                    name = "SPG-9 Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Asst_Gunner_SPG_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Gunner_SPG_01";
                    };
                };

                class cfp_o_hezbollah_infantry_mortar_team {
                    name = "Mortar Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Asst_Gunner_Mortar_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Gunner_Mortar_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized";

                class cfp_o_hezbollah_motorized_squad_militia {
                    name = "Motorized Squad [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Truck_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Medic_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Machine_Gunner_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Explosive_Specialist_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                };

                class cfp_o_hezbollah_motorized_fire_team_militia {
                    name = "Motorized Fire Team [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Machine_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_motorized_squad_paramilitary {
                    name = "Motorized Squad [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Truck_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Medic_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Explosive_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_motorized_fire_team_paramilitary {
                    name = "Motorized Fire Team [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Machine_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_motorized_patrol_armed {
                    name = "Motorized Patrol Armed";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_motorized_anti_armor_team {
                    name = "Motorized TOW Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Quad_Bike_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Gunner_TOW_01";
                    };
                };

                class cfp_o_hezbollah_motorized_anti_armor_team2 {
                    name = "Motorized Hilux AT Team";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_Metis_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_motorized_anti_air_team_zu_23 {
                    name = "Motorized Anti-Air Team [ZU 23]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_ZU_23_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

                class cfp_o_hezbollah_mechanized_squad_btr_paramilitary {
                    name = "Mechanized Squad BTR [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_BTR_60PB_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Medic_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Explosive_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_mechanized_squad_bmp_paramilitary {
                    name = "Mechanized Squad BMP [Paramilitary]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_BMP_2_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Medic_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Explosive_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_mechanized_squad_bmp_militia {
                    name = "Mechanized Squad BMP [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_BMP_2_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Explosive_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

                class cfp_o_hezbollah_mechanized_squad_btr_militia {
                    name = "Mechanized Squad BTR [Militia]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_BTR_60PB_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Explosive_Specialist_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Militia_Rifleman_01";
                    };
                };

            };

            class Armored {
                name = "Armored";

                class cfp_o_hezbollah_armored_armor_section_t72 {
                    name = "Armor Section [T-72]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_T72_01";
                    };
                    class Unit1 {
                        position[] = {9,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_T72_01";
                    };
                };

                class cfp_o_hezbollah_armored_armor_section_t55 {
                    name = "Armor Section [T-55]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_T55_01";
                    };
                    class Unit1 {
                        position[] = {9,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_T55_01";
                    };
                };

                class cfp_o_hezbollah_armored_armor_section_mixed {
                    name = "Armor Section [Mixed]";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_T72_01";
                    };
                    class Unit1 {
                        position[] = {9,-16,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_T55_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class cfp_o_hezbollah_artillery_motorized_mlrs_hilux_battery {
                    name = "Motorized MLRS Hilux Battery";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_MLRS_01";
                    };
                };

                class cfp_o_hezbollah_artillery_motorized_mortar_hilux_battery {
                    name = "Motorized Mortar Hilux Battery";
                    side = 0;
                    faction = "CFP_O_HEZBOLLAH";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_HEZBOLLAH_Hilux_Podnos_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};