class CfgPatches {
    class CFP_O_HEZBOLLAH {
        units[] = {
            "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_01",
            "CFP_O_HEZBOLLAH_Paramilitary_Squad_Leader_01",
            "CFP_O_HEZBOLLAH_Paramilitary_Rifleman_AT_01",
            "CFP_O_HEZBOLLAH_Paramilitary_Medic_01",
            "CFP_O_HEZBOLLAH_Paramilitary_Grenadier_01",
            "CFP_O_HEZBOLLAH_Paramilitary_Machine_Gunner_01",
            "CFP_O_HEZBOLLAH_Paramilitary_Explosive_Specialist_01",
            "CFP_O_HEZBOLLAH_Paramilitary_Sniper_01",
            "CFP_O_HEZBOLLAH_Militia_Rifleman_01",
            "CFP_O_HEZBOLLAH_Militia_Squad_Leader_01",
            "CFP_O_HEZBOLLAH_Militia_Rifleman_AT_01",
            "CFP_O_HEZBOLLAH_Militia_Grenadier_01",
            "CFP_O_HEZBOLLAH_Militia_Medic_01",
            "CFP_O_HEZBOLLAH_Militia_Machine_Gunner_01",
            "CFP_O_HEZBOLLAH_Militia_Explosive_Specialist_01",
            "CFP_O_HEZBOLLAH_Militia_Sniper_01",
            "CFP_O_HEZBOLLAH_Rifleman_SF_01",
            "CFP_O_HEZBOLLAH_Squad_Leader_SF_01",
            "CFP_O_HEZBOLLAH_Rifleman_AT_SF_01",
            "CFP_O_HEZBOLLAH_Medic_SF_01",
            "CFP_O_HEZBOLLAH_Grenadier_SF_01",
            "CFP_O_HEZBOLLAH_Machine_Gunner_SF_01",
            "CFP_O_HEZBOLLAH_Explosive_Specialist_SF_01",
            "CFP_O_HEZBOLLAH_Sniper_SF_01",
	        "CFP_O_HEZBOLLAH_Gunner_DShKM_01",
            "CFP_O_HEZBOLLAH_Gunner_DShKM_Low_01",
            "CFP_O_HEZBOLLAH_Asst_Gunner_DShKM_01",
            "CFP_O_HEZBOLLAH_Gunner_TOW_01",
            "CFP_O_HEZBOLLAH_Asst_Gunner_TOW_01",
            "CFP_O_HEZBOLLAH_Gunner_Metis_01",
            "CFP_O_HEZBOLLAH_Asst_Gunner_Metis_01",
            "CFP_O_HEZBOLLAH_Gunner_Mortar_01",
            "CFP_O_HEZBOLLAH_Asst_Gunner_Mortar_01",
            "CFP_O_HEZBOLLAH_Gunner_SPG_01",
            "CFP_O_HEZBOLLAH_Asst_Gunner_SPG_01",
	        "CFP_O_HEZBOLLAH_DShKM_01",
            "CFP_O_HEZBOLLAH_DShKM_Low_01",
            "CFP_O_HEZBOLLAH_TOW_AT_01",
            "CFP_O_HEZBOLLAH_SPG_9_01",
	        "CFP_O_HEZBOLLAH_Metis_AT_13_01",
            "CFP_O_HEZBOLLAH_Podnos_2B14_01",
            "CFP_O_HEZBOLLAH_Hilux_01",
            "CFP_O_HEZBOLLAH_Hilux_DShKM_01",
            "CFP_O_HEZBOLLAH_Hilux_SPG_01",
            "CFP_O_HEZBOLLAH_Hilux_Igla_01",
            "CFP_O_HEZBOLLAH_Hilux_Metis_01",
            "CFP_O_HEZBOLLAH_Hilux_Podnos_01",
            "CFP_O_HEZBOLLAH_Hilux_MLRS_01",
            "CFP_O_HEZBOLLAH_Hilux_ZU_23_01",
            "CFP_O_HEZBOLLAH_Hilux_AGS_30_01",
            "CFP_O_HEZBOLLAH_T55_01",
            "CFP_O_HEZBOLLAH_T72_01",
            "CFP_O_HEZBOLLAH_Crew_01",
            "CFP_O_HEZBOLLAH_Ural_ZU_23_01",
            "CFP_O_HEZBOLLAH_BMP_2_01",
            "CFP_O_HEZBOLLAH_Offroad_01",
            "CFP_O_HEZBOLLAH_Offroad_Armed_01",
            "CFP_O_HEZBOLLAH_Truck_01",
            "CFP_O_HEZBOLLAH_ZU_23_01",
            "CFP_O_HEZBOLLAH_Quad_Bike_01",
            "CFP_O_HEZBOLLAH_BTR_60PB_01"
        };
        weapons[] = {};
        requiredAddons[] = {
            "A3_Characters_F",
            "cfp_uniforms",
	        "CUP_Weapons_StaticWeapons",
            "CUP_Creatures_StaticWeapons",
	        "CUP_TrackedVehicles_T55",
            "CUP_TrackedVehicles_T72",
	        "CUP_WheeledVehicles_Ural",
            "CUP_TrackedVehicles_BMP",
            "A3_Soft_F_Offroad_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_Bootcamp_Van_01",
            "A3_Soft_F_Quadbike_01",
            "CUP_WheeledVehicles_BTR60"
	    };
        requiredVersion = REQUIRED_VERSION;
        VERSION_CONFIG;
        authors[] = {"Drew"};
        author = MODULE_AUTHOR;
    };
};
