class CfgPatches {
    class CFP_B_UGARMY {
        units[] = {
            "CFP_B_UGARMY_Crew_01",
            "CFP_B_UGARMY_Rifleman_Light_01",
            "CFP_B_UGARMY_Machine_Gunner_Light_01",
            "CFP_B_UGARMY_Rifleman_AT_Light_01",
            "CFP_B_UGARMY_Squad_Leader_Light_01",
            "CFP_B_UGARMY_Grenadier_Light_01",
            "CFP_B_UGARMY_Engineer_Light_01",
            "CFP_B_UGARMY_Explosive_Specialist_Light_01",
            "CFP_B_UGARMY_Medic_Light_01",
            "CFP_B_UGARMY_Rifleman_01",
            "CFP_B_UGARMY_Rifleman_AT_01",
            "CFP_B_UGARMY_Squad_Leader_01",
            "CFP_B_UGARMY_Machine_Gunner_01",
            "CFP_B_UGARMY_Grenadier_01",
            "CFP_B_UGARMY_Engineer_01",
            "CFP_B_UGARMY_Explosive_Specialist_01",
            "CFP_B_UGARMY_Medic_01",
            "CFP_B_UGARMY_Helicopter_Pilot_01",
            "CFP_B_UGARMY_Mi_24D_01",
            "CFP_B_UGARMY_Mi_17_01",
            "CFP_B_UGARMY_Mi_17_VIV_01",
            "CFP_B_UGARMY_T55_01",
            "CFP_B_UGARMY_BMP_2_01",
            "CFP_B_UGARMY_BRDM_2_01",
            "CFP_B_UGARMY_Ural_01",
            "CFP_B_UGARMY_Ural_Refuel_01",
            "CFP_B_UGARMY_Ural_Repair_01",
            "CFP_B_UGARMY_Ural_Ammo_01",
            "CFP_B_UGARMY_Ural_Open_01",
            "CFP_B_UGARMY_BM_21_01",
            "CFP_B_UGARMY_Ural_ZU_23_01",
            "CFP_B_UGARMY_RG_31_01",
            "CFP_B_UGARMY_UAZ_Open_01",
            "CFP_B_UGARMY_UAZ_DShKM_01",
            "CFP_B_UGARMY_UAZ_SPG_01",
            "CFP_B_UGARMY_UAZ_01",
            "CFP_B_UGARMY_T90_01",
            "CFP_B_UGARMY_Operator_01",
            "CFP_B_UGARMY_Operator_Team_Leader_01",
            "CFP_B_UGARMY_Operator_Medic_01",
            "CFP_B_UGARMY_Operator_Explosive_Specialist_01",
            "CFP_B_UGARMY_Gunner_DShKM_01",
            "CFP_B_UGARMY_Asst_Gunner_DShKM_01",
            "CFP_B_UGARMY_Gunner_Mortar_01",
            "CFP_B_UGARMY_Asst_Gunner_Mortar_01",
            "CFP_B_UGARMY_Gunner_SPG_01",
            "CFP_B_UGARMY_Asst_Gunner_SPG_01",
            "CFP_B_UGARMY_DShKM_Minitripod_01",
            "CFP_B_UGARMY_DShKM_01",
            "CFP_B_UGARMY_Podnos_2B14_01",
            "CFP_B_UGARMY_SPG_9_01",
            "CFP_B_UGARMY_D30_AT_01",
            "CFP_B_UGARMY_ZU_23_01",
            "CFP_B_UGARMY_BTR_90_01",
            "CFP_B_UGARMY_BTR_60_01",
            "CFP_B_UGARMY_Sniper_01"
        };
        weapons[] = {};
        requiredAddons[] = {
            "CFP_O_HEZBOLLAH",
            "CFP_B_NAARMY",
            "CFP_O_BOKOHARAM",
            "CFP_O_ALSHABAAB",
            "CFP_O_ALQAEDA",
            "CFP_B_USMC_DES",
            "CFP_B_KEARMY",
            "CFP_O_RUARMY_DES",
            "A3_Characters_F",
            "CUP_Weapons_StaticWeapons",
            "CUP_WheeledVehicles_BTR90",
            "cfp_vehicles",
            "CUP_WheeledVehicles_BTR60",
            "cfp_uniforms"
        };
        requiredVersion = REQUIRED_VERSION;
        VERSION_CONFIG;
        authors[] = {"Drew"};
        author = MODULE_AUTHOR;
    };
};
