class CfgPatches {
    class CFP_B_MLARMY {
        units[] = {
            "CFP_B_MLARMY_Rifleman_01",
            "CFP_B_MLARMY_Squad_Leader_01",
            "CFP_B_MLARMY_Rifleman_AT_01",
            "CFP_B_MLARMY_Machine_Gunner_01",
            "CFP_B_MLARMY_Grenadier_01",
            "CFP_B_MLARMY_Explosive_Specialist_01",
            "CFP_B_MLARMY_Medic_01",
            "CFP_B_MLARMY_Sniper_01",
            "CFP_B_MLARMY_Crew_01",
            "CFP_B_MLARMY_Helicopter_Pilot_01",
            "CFP_B_MLARMY_SF_Rifleman_01",
            "CFP_B_MLARMY_SF_Team_Leader_01",
            "CFP_B_MLARMY_SF_Machine_Gunner_01",
            "CFP_B_MLARMY_SF_Explosive_Specialist_01",
            "CFP_B_MLARMY_SF_Medic_01",
            "CFP_B_MLARMY_Officer_01",
            "CFP_B_MLARMY_Gunner_DShKM_01",
            "CFP_B_MLARMY_Asst_Gunner_DShKM_01",
            "CFP_B_MLARMY_Gunner_Mortar_01",
            "CFP_B_MLARMY_Asst_Gunner_Mortar_01",
            "CFP_B_MLARMY_DShKM_01",
            "CFP_B_MLARMY_Podnos_2B14_01",
            "CFP_B_MLARMY_DShKM_Mini_tripod_01",
            "CFP_B_MLARMY_D30_01",
            "CFP_B_MLARMY_SPG_9_01",
            "CFP_B_MLARMY_Technical_Armed_01",
            "CFP_B_MLARMY_Technical_01",
            "CFP_B_MLARMY_Truck_01",
            "CFP_B_MLARMY_Technical_AT_01",
            "CFP_B_MLARMY_Ural_01",
            "CFP_B_MLARMY_Ural_Ammo_01",
            "CFP_B_MLARMY_Ural_Refuel_01",
            "CFP_B_MLARMY_Ural_Repair_01",
            "CFP_B_MLARMY_Ural_Open_01",
            "CFP_B_MLARMY_Land_Rover_Ambulance_01",
            "CFP_B_MLARMY_T34_01",
            "CFP_B_MLARMY_T55_01",
            "CFP_B_MLARMY_BTR_60PB_01",
            "CFP_B_MLARMY_BTR_40_Unarmed_01",
            "CFP_B_MLARMY_BTR_40_DShKM_01",
            "CFP_B_MLARMY_BRDM_2_01",
            "CFP_B_MLARMY_UAZ_01",
            "CFP_B_MLARMY_Ural_ZU_23_01",
            "CFP_B_MLARMY_Harbin_ZB_9_01",
            "CFP_B_MLARMY_Mi_35_01",
            "CFP_B_MLARMY_SA_330_Puma_01",
            "CFP_B_MLARMY_RG_31_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "cfp_uniforms",
            "CUP_Weapons_StaticWeapons",
            "cfp_vehicles",
            "CUP_WheeledVehicles_Datsun",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_Bootcamp_Van_01",
            "A3_Soft_F_Offroad_01",
            "CUP_WheeledVehicles_Ural",
            "CUP_TrackedVehicles_T34",
            "CUP_TrackedVehicles_T55",
            "CUP_WheeledVehicles_BTR60",
            "CUP_WheeledVehicles_BTR40",
            "CUP_WheeledVehicles_BRDM2",
            "CUP_WheeledVehicles_UAZ",
            "A3_Air_F_Heli_Light_02",
            "CUP_AirVehicles_Mi24",
            "CUP_AirVehciles_SA330",
            "CUP_WheeledVehicles_RG31"
        };
        author = "Drew";
        authors[] = {"Drew"};
    };
};