class CfgWorlds {
	class GenericNames
	{
		class IsraelNames
		{
			class FirstNames
			{
				ABE	= "Abe";
				ABRAHAM	= "Abraham";
				ALUV = "Aluv";
				AMIKAM	= "Amikam";
                AVIV  = "Aviv";
				AMIR	= "Amir";
				AHARON	= "Aharon";
				ARIELLA	= "Ariella";
				ARI	= "Ari";
				BENJAMIN	= "Benjamin";
				ELI	= "Eli";
				NADAV	= "Nadav";
				BRUNO	= "Bruno";
				YAACOV	= "Yaacov";
				YOEL	= "Yoel";
				GEORGE	= "George";
				HERZI 	= "Herzi";
				LUKE	= "Luke";
				MATTHEW	= "Matthew";
				DAVID	= "David";
				DANIEL	= "Daniel";
				LIOR	= "Lior";
				ELIAS	= "Elias";
				EYAL	= "Eyal";
				YAIR	= "Yair";
				MUNI 	= "Muni";
				HERNAN	= "Hernan";
				RONEN 	= "Ronen";
				GADI	= "Gadi";
				DORON 	= "Leon";
				ELIEZER = "Eliezer";
				JOSEPH	= "Joseph";
				JACOB    = "Jacob";
				SCHMOOL	= "Schmool";
				TEO	    = "Teo";
				TAMIR	= "Tamir";
				JOSHUA	= "Joshua";
				STEVEN = "Steven";
			};
			class LastNames
			{
				AMAR = "Amar";
				AZOULAI = "Azoulai";
				ASHKENAZI = "Ashkenazi";
				ABRAHAM = "Abraham";
				ATIAS = "Atias";
				BARR = "Barr";
				BITON = "Biton";
				BACHAR = "Bachar";
				BINYAMIN = "Binyamin";
				BARUCH = "Baruch";
				ASSOULINE = "Assouline";
				CHEN = "Chen";
				COHEN = "Cohen";
				DOHAN = "Dohan";
				DAYAN = "Dayan";
				DADON = "Dadan";
				EZRA = "Ezra";
				ELIYAHU = "Eliyahu";
				ELBAZ = "Elbaz";
				FELDMAN = "Feldman";
				FRIEDMAN = "Friedman";
				GABBAI = "Gabbai";
				GOLAN = "Golan";
				GUTIERREZ = "Gutierrez";
				GREENBERG = "Greenberg";
				GOLDBERG = "Goldberg";
				GROSS = "Gross";
				HERSHKOWITZ = "Hershkowitz";
				HAROSH  = "Harosh";
				HAREL = "Harel";
				HAZAN = "Hazan";
				HADAD = "Hadad";
				HAIM = "Haim";
				ISAAC = "Isaac";
				ISRAEL = "Israel";
				KATZ = "Katz";
				KLEIN  = "Klein";
				KADOSH  = "Kadosh";
				KAPLAN = "Kaplan";
				LAVI = "Lavi";
				LEVINE = "Levine";
				LEVY = "Levy";
				MALKA = "Malka";
				MOSHE = "Moshe";
				MOR = "Mor";
				MAIMON = "Maimon";
				MEIR = "Meir";
				MILLER = "Miller";
				MIZRACHI = "Mizrachi";
				NACHUM = "Nachum";
				OHAYON = "Ohayon";
				OHANA = "Ohana";
				OVADIA = "Ovadia";
				OREN = "Oren";
				PERETZ = "Peretz";
				ROSEN = "Rosen";
				RACHAMIM = "Rachamim";
				RABINOWITZ = "Rabinowitz";
				RUBIN = "Rubin";
				ROSENBERG = "Rosenberg";
				SPIRA = "Spira";
				SEGAL = "Segal";
				SHALOM = "Shalom";
				SUISSA = "Suissa";
				SHEMESH = "Shemesh";
				STERN = "Stern";
				SCHWARTZ = "Schwartz";
				SHAHAR = "Shahar";
				SHARABI = "Sharabi";
				SOFER = "Sofer";
				SOLOMON = "Solomon";
				TZUR = "Tzur";
				TAL = "Tal";
				YITZCHAK = "Yitzchak";
				VAKNIN = "Vaknin";
				YISRAEL = "Yisrael";
				YIFRAH = "Yifrah";
				WEISS = "Weiss";
				YITZHAKI = "Yitzhaki";
				YECHEZKEL = "Yechezkel";
			};
		};
	};
};