#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define true	1
#define false	0

#define VSoft		0
#define VArmor		1
#define VAir		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

class CfgPatches
{
	class CFP_Uniforms
	{
		units[] = {
			"C_Driver_1_black_F",
			"C_Driver_1_blue_F",
			"C_Driver_1_green_F",
			"C_Driver_1_red_F",
			"C_Driver_1_white_F",
			"C_Driver_1_yellow_F",
			"C_Driver_1_orange_F",
			"SP_0000_Standard_BattleDressUniform_Black",
			"SP_0000_Standard_BattleDressUniform_Green",
			"SP_0000_Standard_BattleDressUniform_Tan",
			"SP_0000_Standard_BattleDressUniform_Grey",
			"SP_0000_Standard_BattleDressUniform_BlueDark",
			"SP_0000_Standard_BattleDressUniform_BlueFrost",
			"SP_0000_Standard_BattleDressUniform_GreenOlive",
			"SP_0000_Standard_BattleDressUniform_Hunter",
			"SP_0000_Standard_BattleDressUniform_Hunter2",
			"SP_0000_Standard_BattleDressUniform_ATacsFG",
			"SP_0000_Standard_BattleDressUniform_NodUrban",
			"SP_0000_Standard_Coverall_Black",
			"SP_0000_Standard_Coverall_Green",
			"SP_0000_Standard_Coverall_Tan",
			"SP_0000_Standard_Coverall_Grey",
			"SP_0000_Standard_Coverall_BlueDark",
			"SP_0000_Standard_Coverall_BlueFrost",
			"SP_0000_Standard_Coverall_GreenOlive",
			"SP_0000_Standard_Coverall_White",
			"SP_0000_Standard_Coverall_Red",
			"SP_0000_Standard_Coverall_Yellow",
			"SP_0000_Standard_Coverall_Brown",
			"SP_0000_Standard_Coverall_Orange",
			"SP_0000_Standard_DiverUniform_Black",
			"SP_0000_Standard_DiverUniform_Green",
			"SP_0000_Standard_DiverUniform_Tan",
			"SP_0000_Standard_DiverUniform_Grey",
			"SP_0000_Standard_DiverUniform_BlueDark",
			"SP_0000_Standard_DiverUniform_BlueFrost",
			"SP_0000_Standard_DiverUniform_GreenOlive",
			"SP_0000_Standard_DiverUniform_Hunter",
			"SP_0000_Standard_DiverUniform_Hunter2",
			"SP_0000_Standard_DiverUniform_ATacsFG",
			"SP_0000_Standard_DiverUniform_NodUrban",
			"SP_0000_Standard_FieldUniform_Black",
			"SP_0000_Standard_FieldUniform_Black_SS",
			"SP_0000_Standard_FieldUniform_Green",
			"SP_0000_Standard_FieldUniform_Green_SS",
			"SP_0000_Standard_FieldUniform_Tan",
			"SP_0000_Standard_FieldUniform_Tan_SS",
			"SP_0000_Standard_FieldUniform_Grey",
			"SP_0000_Standard_FieldUniform_Grey_SS",
			"SP_0000_Standard_FieldUniform_BlueDark",
			"SP_0000_Standard_FieldUniform_BlueDark_SS",
			"SP_0000_Standard_FieldUniform_BlueFrost",
			"SP_0000_Standard_FieldUniform_BlueFrost_SS",
			"SP_0000_Standard_FieldUniform_GreenOlive",
			"SP_0000_Standard_FieldUniform_GreenOlive_SS",
			"SP_0000_Standard_FieldUniform_Hunter",
			"SP_0000_Standard_FieldUniform_Hunter_SS",
			"SP_0000_Standard_FieldUniform_Hunter2",
			"SP_0000_Standard_FieldUniform_Hunter2_SS",
			"SP_0000_Standard_FieldUniform_ATacsFG",
			"SP_0000_Standard_FieldUniform_ATacsFG_SS",
			"SP_0000_Standard_FieldUniform_NodUrban",
			"SP_0000_Standard_FieldUniform_NodUrban_SS",
			"SP_0000_Standard_PulloverUniform_Black",
			"SP_0000_Standard_PulloverUniform_Green",
			"SP_0000_Standard_PulloverUniform_Tan",
			"SP_0000_Standard_PulloverUniform_Grey",
			"SP_0000_Standard_PulloverUniform_BlueDark",
			"SP_0000_Standard_PulloverUniform_BlueFrost",
			"SP_0000_Standard_PulloverUniform_GreenOlive",
			"SP_0000_Standard_PulloverUniform_Hunter",
			"SP_0000_Standard_PulloverUniform_Hunter2",
			"SP_0000_Standard_PulloverUniform_ATacsFG",
			"SP_0000_Standard_PulloverUniform_NodUrban",
			"SP_0000_Standard_ReconUniform_Black",
			"SP_0000_Standard_ReconUniform_Green",
			"SP_0000_Standard_ReconUniform_Tan",
			"SP_0000_Standard_ReconUniform_Grey",
			"SP_0000_Standard_ReconUniform_BlueDark",
			"SP_0000_Standard_ReconUniform_BlueFrost",
			"SP_0000_Standard_ReconUniform_GreenOlive",
			"SP_0000_Standard_ReconUniform_Hunter",
			"SP_0000_Standard_ReconUniform_Hunter2",
			"SP_0000_Standard_ReconUniform_ATacsFG",
			"SP_0000_Standard_ReconUniform_NodUrban",
			"SP_0000_Standard_WorkUniform_Hunter",
			"SP_0000_Standard_WorkUniform_ATacsFG",
			"SP_0000_Standard_WorkUniform_NodUrban",
			"SP_0000_Standard_TacticalUniform_Black",
			"SP_0000_Standard_TacticalUniform_Black_SS",
			"SP_0000_Standard_TacticalUniform_Black_TS",
			"SP_0000_Standard_TacticalUniform_Green",
			"SP_0000_Standard_TacticalUniform_Green_SS",
			"SP_0000_Standard_TacticalUniform_Green_TS",
			"SP_0000_Standard_TacticalUniform_Tan",
			"SP_0000_Standard_TacticalUniform_Tan_SS",
			"SP_0000_Standard_TacticalUniform_Tan_TS",
			"SP_0000_Standard_TacticalUniform_Grey",
			"SP_0000_Standard_TacticalUniform_Grey_SS",
			"SP_0000_Standard_TacticalUniform_Grey_TS",
			"SP_0000_Standard_TacticalUniform_BlueDark",
			"SP_0000_Standard_TacticalUniform_BlueDark_SS",
			"SP_0000_Standard_TacticalUniform_BlueDark_TS",
			"SP_0000_Standard_TacticalUniform_BlueFrost",
			"SP_0000_Standard_TacticalUniform_BlueFrost_SS",
			"SP_0000_Standard_TacticalUniform_BlueFrost_TS",
			"SP_0000_Standard_TacticalUniform_GreenOlive",
			"SP_0000_Standard_TacticalUniform_GreenOlive_SS",
			"SP_0000_Standard_TacticalUniform_GreenOlive_TS",
			"SP_0000_Standard_TacticalUniform_Hunter",
			"SP_0000_Standard_TacticalUniform_Hunter_SS",
			"SP_0000_Standard_TacticalUniform_Hunter_TS",
			"SP_0000_Standard_TacticalUniform_Hunter2",
			"SP_0000_Standard_TacticalUniform_Hunter2_SS",
			"SP_0000_Standard_TacticalUniform_Hunter2_TS",
			"SP_0000_Standard_TacticalUniform_ATacsFG",
			"SP_0000_Standard_TacticalUniform_ATacsFG_SS",
			"SP_0000_Standard_TacticalUniform_ATacsFG_TS",
			"SP_0000_Standard_TacticalUniform_NodUrban",
			"SP_0000_Standard_TacticalUniform_NodUrban_SS",
			"SP_0000_Standard_TacticalUniform_NodUrban_TS",
			"SP_0000_Standard_Underwear_Black",
			"SP_0000_Standard_Underwear_Green",
			"SP_0000_Standard_Underwear_Tan",
			"SP_0000_Standard_Underwear_Grey",
			"SP_0000_Standard_Underwear_BlueDark",
			"SP_0000_Standard_Underwear_BlueFrost",
			"SP_0000_Standard_Underwear_BlueSky",
			"SP_0000_Standard_Underwear_GreenOlive",
			"SP_0000_Standard_Underwear_GreenSpring",
			"SP_0000_Standard_Underwear_Brown",
			"SP_0000_Standard_Underwear_Olive",
			"SP_0000_Standard_Underwear_Orange",
			"SP_0000_Standard_Underwear_Pink",
			"SP_0000_Standard_Underwear_Purple",
			"SP_0000_Standard_Underwear_Red",
			"SP_0000_Standard_Underwear_White",
			"SP_0000_Standard_Underwear_Yellow"
		};
		weapons[] = {
			"SP_0000_Standard_BattleDressUniform_Black",
			"SP_0000_Standard_BattleDressUniform_Green",
			"SP_0000_Standard_BattleDressUniform_Tan",
			"SP_0000_Standard_BattleDressUniform_Grey",
			"SP_0000_Standard_BattleDressUniform_BlueDark",
			"SP_0000_Standard_BattleDressUniform_BlueFrost",
			"SP_0000_Standard_BattleDressUniform_GreenOlive",
			"SP_0000_Standard_BattleDressUniform_Hunter",
			"SP_0000_Standard_BattleDressUniform_Hunter2",
			"SP_0000_Standard_BattleDressUniform_ATacsFG",
			"SP_0000_Standard_BattleDressUniform_NodUrban",
			"SP_0000_Standard_Coverall_Black",
			"SP_0000_Standard_Coverall_Green",
			"SP_0000_Standard_Coverall_Tan",
			"SP_0000_Standard_Coverall_Grey",
			"SP_0000_Standard_Coverall_BlueDark",
			"SP_0000_Standard_Coverall_BlueFrost",
			"SP_0000_Standard_Coverall_GreenOlive",
			"SP_0000_Standard_Coverall_White",
			"SP_0000_Standard_Coverall_Red",
			"SP_0000_Standard_Coverall_Yellow",
			"SP_0000_Standard_Coverall_Brown",
			"SP_0000_Standard_Coverall_Orange",
			"SP_0000_Standard_DiverUniform_Black",
			"SP_0000_Standard_DiverUniform_Green",
			"SP_0000_Standard_DiverUniform_Tan",
			"SP_0000_Standard_DiverUniform_Grey",
			"SP_0000_Standard_DiverUniform_BlueDark",
			"SP_0000_Standard_DiverUniform_BlueFrost",
			"SP_0000_Standard_DiverUniform_GreenOlive",
			"SP_0000_Standard_DiverUniform_Hunter",
			"SP_0000_Standard_DiverUniform_Hunter2",
			"SP_0000_Standard_DiverUniform_ATacsFG",
			"SP_0000_Standard_DiverUniform_NodUrban",
			"SP_0000_Standard_FieldUniform_Black",
			"SP_0000_Standard_FieldUniform_Black_SS",
			"SP_0000_Standard_FieldUniform_Green",
			"SP_0000_Standard_FieldUniform_Green_SS",
			"SP_0000_Standard_FieldUniform_Tan",
			"SP_0000_Standard_FieldUniform_Tan_SS",
			"SP_0000_Standard_FieldUniform_Grey",
			"SP_0000_Standard_FieldUniform_Grey_SS",
			"SP_0000_Standard_FieldUniform_BlueDark",
			"SP_0000_Standard_FieldUniform_BlueDark_SS",
			"SP_0000_Standard_FieldUniform_BlueFrost",
			"SP_0000_Standard_FieldUniform_BlueFrost_SS",
			"SP_0000_Standard_FieldUniform_GreenOlive",
			"SP_0000_Standard_FieldUniform_GreenOlive_SS",
			"SP_0000_Standard_FieldUniform_Hunter",
			"SP_0000_Standard_FieldUniform_Hunter_SS",
			"SP_0000_Standard_FieldUniform_Hunter2",
			"SP_0000_Standard_FieldUniform_Hunter2_SS",
			"SP_0000_Standard_FieldUniform_ATacsFG",
			"SP_0000_Standard_FieldUniform_ATacsFG_SS",
			"SP_0000_Standard_FieldUniform_NodUrban",
			"SP_0000_Standard_FieldUniform_NodUrban_SS",
			"SP_0000_Standard_PulloverUniform_Black",
			"SP_0000_Standard_PulloverUniform_Green",
			"SP_0000_Standard_PulloverUniform_Tan",
			"SP_0000_Standard_PulloverUniform_Grey",
			"SP_0000_Standard_PulloverUniform_BlueDark",
			"SP_0000_Standard_PulloverUniform_BlueFrost",
			"SP_0000_Standard_PulloverUniform_GreenOlive",
			"SP_0000_Standard_PulloverUniform_Hunter",
			"SP_0000_Standard_PulloverUniform_Hunter2",
			"SP_0000_Standard_PulloverUniform_ATacsFG",
			"SP_0000_Standard_PulloverUniform_NodUrban",
			"SP_0000_Standard_ReconUniform_Black",
			"SP_0000_Standard_ReconUniform_Green",
			"SP_0000_Standard_ReconUniform_Tan",
			"SP_0000_Standard_ReconUniform_Grey",
			"SP_0000_Standard_ReconUniform_BlueDark",
			"SP_0000_Standard_ReconUniform_BlueFrost",
			"SP_0000_Standard_ReconUniform_GreenOlive",
			"SP_0000_Standard_ReconUniform_Hunter",
			"SP_0000_Standard_ReconUniform_Hunter2",
			"SP_0000_Standard_ReconUniform_ATacsFG",
			"SP_0000_Standard_ReconUniform_NodUrban",
			"SP_0000_Standard_WorkUniform_Hunter",
			"SP_0000_Standard_WorkUniform_Hunter2",
			"SP_0000_Standard_WorkUniform_ATacsFG",
			"SP_0000_Standard_WorkUniform_NodUrban",
			"SP_0000_Standard_TacticalUniform_Black",
			"SP_0000_Standard_TacticalUniform_Black_SS",
			"SP_0000_Standard_TacticalUniform_Black_TS",
			"SP_0000_Standard_TacticalUniform_Green",
			"SP_0000_Standard_TacticalUniform_Green_SS",
			"SP_0000_Standard_TacticalUniform_Green_TS",
			"SP_0000_Standard_TacticalUniform_Tan",
			"SP_0000_Standard_TacticalUniform_Tan_SS",
			"SP_0000_Standard_TacticalUniform_Tan_TS",
			"SP_0000_Standard_TacticalUniform_Grey",
			"SP_0000_Standard_TacticalUniform_Grey_SS",
			"SP_0000_Standard_TacticalUniform_Grey_TS",
			"SP_0000_Standard_TacticalUniform_BlueDark",
			"SP_0000_Standard_TacticalUniform_BlueDark_SS",
			"SP_0000_Standard_TacticalUniform_BlueDark_TS",
			"SP_0000_Standard_TacticalUniform_BlueFrost",
			"SP_0000_Standard_TacticalUniform_BlueFrost_SS",
			"SP_0000_Standard_TacticalUniform_BlueFrost_TS",
			"SP_0000_Standard_TacticalUniform_GreenOlive",
			"SP_0000_Standard_TacticalUniform_GreenOlive_SS",
			"SP_0000_Standard_TacticalUniform_GreenOlive_TS",
			"SP_0000_Standard_TacticalUniform_Hunter",
			"SP_0000_Standard_TacticalUniform_Hunter_SS",
			"SP_0000_Standard_TacticalUniform_Hunter_TS",
			"SP_0000_Standard_TacticalUniform_Hunter2",
			"SP_0000_Standard_TacticalUniform_Hunter2_SS",
			"SP_0000_Standard_TacticalUniform_Hunter2_TS",
			"SP_0000_Standard_TacticalUniform_ATacsFG",
			"SP_0000_Standard_TacticalUniform_ATacsFG_SS",
			"SP_0000_Standard_TacticalUniform_ATacsFG_TS",
			"SP_0000_Standard_TacticalUniform_NodUrban",
			"SP_0000_Standard_TacticalUniform_NodUrban_SS",
			"SP_0000_Standard_TacticalUniform_NodUrban_TS",
			"SP_0000_Standard_Underwear_Black",
			"SP_0000_Standard_Underwear_Green",
			"SP_0000_Standard_Underwear_Tan",
			"SP_0000_Standard_Underwear_Grey",
			"SP_0000_Standard_Underwear_BlueDark",
			"SP_0000_Standard_Underwear_BlueFrost",
			"SP_0000_Standard_Underwear_BlueSky",
			"SP_0000_Standard_Underwear_GreenOlive",
			"SP_0000_Standard_Underwear_GreenSpring",
			"SP_0000_Standard_Underwear_Brown",
			"SP_0000_Standard_Underwear_Olive",
			"SP_0000_Standard_Underwear_Orange",
			"SP_0000_Standard_Underwear_Pink",
			"SP_0000_Standard_Underwear_Purple",
			"SP_0000_Standard_Underwear_Red",
			"SP_0000_Standard_Underwear_White",
			"SP_0000_Standard_Underwear_Yellow"
		};
		
		requiredVersion = 1.70;
		requiredAddons[] = {"A3_Data_F","A3_Weapons_F","A3_Characters_F","A3_Characters_F_BLUFOR"};
	};
};

#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
