//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 176.143187 on Stable branch
// Generated with ALiVE version 1.5.0.1711091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class CFP_B_KEARMY {
        displayName = "Kenyan Defense Force";
        side = 1;
        flag = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        priority = 0;
    };
};