class CfgWorlds {
	class GenericNames
	{
		class FrenchNames
		{
			class FirstNames
			{
				AARON	= "Aaron";
				ADAM	= "Adam";
				ABEL = "Abel";
				ADEL	= "Adel";
                ADRIAN  = "Adrien";
				ANDRES	= "Andres";
				ANDRE	= "Andre";
				ARNAUD	= "Arnaud";
				BAPTISTE	= "Baptiste";
				BENJAMIN	= "Benjamin";
				BENOIT	= "Benoit";
				BRANDON	= "Brandon";
				CAMERON	= "Cameron";
				CLAUDE	= "Claude";
				CHARLES	= "Charles";
				CHRISTOPHER	= "Christopher";
				DAMIEN 	= "Damien";
				DANIEL	= "Daniel";
				MATTHEW	= "Matthew";
				DAVID	= "David";
				DORIAN	= "Dorian";
				EDUOARD	= "Eduoard";
				EMILE	= "Emile";
				ESTEBAN	= "Esteban";
				FABIEN 	= "Fabien";
				FLORIEN	= "Florien";
				FRANCOIS = "Francois";
				GASPARD	= "Gaspard";
				GAUTIER = "Gautier";
				GREGORY = "Gregory";
				JOSEPH	= "Joseph";
				JACOB    = "Jacob";
				HENRI	= "Henri";
				JEAN	= "Jean";
				JAMES	= "James";
				JOSHUA	= "Joshua";
				JULIAN = "Julian";
				LEON = "Leon";
				LOUIS = "Louis";
				MICHELLE = "Michelle";
				NICOLAS = "Nicolas";
				PIERRE = "Pierre";
				RAFAEL = "Rafael";
				SEBASTIEN = "Sebastien";
				TRISTAN = "Tristan";
				VINCENT = "Vincent";
			};
			class LastNames
			{
				ALBERT = "Albert";
				ALLARD = "Allard";
				ANDRES = "Andres";
				ABRAHAM = "Abraham";
				ATIAS = "Atias";
				AUGUSTIN = "Augustin";
				BITON = "Biton";
				BABINEAUX = "Babineaux";
				BEAUFORT = "Beaufort";
				BERNARD = "Bernard";
				BOUCHER = "Boucher";
				BONAPARTE = "Bonaparte";
				CARON = "Caron";
				CHASTAIN = "Chastain";
				COLBERT = "Colbert";
				COUTURE = "Couture";
				COUSTEAU = "Cousteau";
				DANIEL = "Daniel";
				DAVID = "David";
				DELACROIX = "Delacroix";
				DELAFONTAINE = "De La Fontaine";
				DUBOIS = "Dubois";
				DUMONT = "Dumont";
				EMILE = "Emile";
				FABIEN = "Fabien";
				FAVREAU = "Favreau";
				FELIX = "Felix";
				FRANCOIS = "Francois";
				GAGNON = "Gagnon";
				GOLAN = "Golan";
				GEROUX = "Geroux";
				GOSSELIN = "Gosselin";
				HEBERT = "Hebert";
				HARDY = "Hardy";
				JACQUES = "Jacques";
				JANVIER  = "Janvier";
				JORDAN = "Jordan";
				LACHAPHELLE = "Lachapelle";
				LAMAR = "Lamar";
				LAMBERT = "Lambert";
				ISAAC = "Isaac";
				LAURENT = "Laurent";
				LEBLANC = "Leblanc";
				LYON  = "Lyon";
				MARIE  = "Marie";
				MARTEL = "Martel";
				MARCHAND = "Marchand";
				MARTIN = "Martin";
				MATTHIEU = "Matthieu";
				MOREAU = "Moreau";
				NICOLAS = "Nicolas";
				NEY = "Ney";
				NOEL = "Noel";
				OLIVIER = "Olivier";
				PAGET = "Paget";
				PASCAL = "Pascal";
				PAUL = "Paul";
				POULIN = "Poulin";
				REYNAUD = "Reynaud";
				ROBERT = "Robert";
				ROCHELLE = "Rochelle";
				ROUSSEAU = "Rousseau";
				ROUX = "Roux";
				SALMON = "Salmon";
				SAULT = "Sault";
				SEGAL = "Segal";
				SIMON = "Simon";
				STPIERRE = "St Pierre";
				STTHOMAS = "St Thomas";
				SEVERIN = "Severin";
				THEROUX = "Theroux";
				THIBAULT = "Thibault";
				THOMAS = "Thomas";
				TREMBLAY = "Tremblay";
				VICTOR = "Victor";
				VILLANEUVE = "Villaneuve";
				VINCENT = "Vincent";
				VEAUCLAIR = "Veauclair";
				SOUCY = "Soucy";
				GROUCHY = "Grouchy";
				GEAUTIEAU = "Geautieau";
				GARCON = "Garcon";
				LECOUNT = "Lecount";
				MARCEAU = "Marceau";
				BAPTISTE = "Baptiste";
			};
		};
	};
};