#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define true	1
#define false	0

#define VSoft		0
#define VArmor		1
#define VAir		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define private		0
#define protected		1
#define public		2

class CfgPatches
{
	class CFP_Uniforms_AFG
	{
		units[] = {
			"AFG_1980DuckHunter_BattleDressUniform",
			"AFG_1980DuckHunter_PulloverUniform",
			"AFG_1980DuckHunter_ReconUniform",
			"AFG_1980DuckHunter_FieldUniform",
			"AFG_1980DuckHunter_FieldUniform_SS",
			"AFG_1980DuckHunter_TacticalUniform",
			"AFG_1980DuckHunter_TacticalUniform_SS",
			"AFG_1980DuckHunter_TacticalUniform_TS",
			"AFG_1990DuckHunter_BattleDressUniform",
			"AFG_1990DuckHunter_PulloverUniform",
			"AFG_1990DuckHunter_ReconUniform",
			"AFG_1990DuckHunter_FieldUniform",
			"AFG_1990DuckHunter_FieldUniform_SS",
			"AFG_1990DuckHunter_TacticalUniform",
			"AFG_1990DuckHunter_TacticalUniform_SS",
			"AFG_1990DuckHunter_TacticalUniform_TS",
			"AFG_1996DPM_BattleDressUniform",
			"AFG_1996DPM_PulloverUniform",
			"AFG_1996DPM_ReconUniform",
			"AFG_1996DPM_FieldUniform",
			"AFG_1996DPM_FieldUniform_SS",
			"AFG_1996DPM_TacticalUniform",
			"AFG_1996DPM_TacticalUniform_SS",
			"AFG_1996DPM_TacticalUniform_TS",
			"AFG_1996DuckHunter_BattleDressUniform",
			"AFG_1996DuckHunter_PulloverUniform",
			"AFG_1996DuckHunter_ReconUniform",
			"AFG_1996DuckHunter_FieldUniform",
			"AFG_1996DuckHunter_FieldUniform_SS",
			"AFG_1996DuckHunter_TacticalUniform",
			"AFG_1996DuckHunter_TacticalUniform_SS",
			"AFG_1996DuckHunter_TacticalUniform_TS",
			"AFG_1996Leaf_BattleDressUniform",
			"AFG_1996Leaf_PulloverUniform",
			"AFG_1996Leaf_ReconUniform",
			"AFG_1996Leaf_FieldUniform",
			"AFG_1996Leaf_FieldUniform_SS",
			"AFG_1996Leaf_TacticalUniform",
			"AFG_1996Leaf_TacticalUniform_SS",
			"AFG_1996Leaf_TacticalUniform_TS",
			"AFG_1996Woodland_BattleDressUniform",
			"AFG_1996Woodland_PulloverUniform",
			"AFG_1996Woodland_ReconUniform",
			"AFG_1996Woodland_FieldUniform",
			"AFG_1996Woodland_FieldUniform_SS",
			"AFG_1996Woodland_TacticalUniform",
			"AFG_1996Woodland_TacticalUniform_SS",
			"AFG_1996Woodland_TacticalUniform_TS",
			"AFG_2001Lizard_BattleDressUniform",
			"AFG_2001Lizard_PulloverUniform",
			"AFG_2001Lizard_ReconUniform",
			"AFG_2001Lizard_FieldUniform",
			"AFG_2001Lizard_FieldUniform_SS",
			"AFG_2001Lizard_TacticalUniform",
			"AFG_2001Lizard_TacticalUniform_SS",
			"AFG_2001Lizard_TacticalUniform_TS",
			"AFG_2002FourColorWoodland_BattleDressUniform",
			"AFG_2002FourColorWoodland_PulloverUniform",
			"AFG_2002FourColorWoodland_ReconUniform",
			"AFG_2002FourColorWoodland_FieldUniform",
			"AFG_2002FourColorWoodland_FieldUniform_SS",
			"AFG_2002FourColorWoodland_TacticalUniform",
			"AFG_2002FourColorWoodland_TacticalUniform_SS",
			"AFG_2002FourColorWoodland_TacticalUniform_TS",
			"AFG_2002Woodland_BattleDressUniform",
			"AFG_2002Woodland_PulloverUniform",
			"AFG_2002Woodland_ReconUniform",
			"AFG_2002Woodland_FieldUniform",
			"AFG_2002Woodland_FieldUniform_SS",
			"AFG_2002Woodland_TacticalUniform",
			"AFG_2002Woodland_TacticalUniform_SS",
			"AFG_2002Woodland_TacticalUniform_TS",
			"AFG_2008GreyChocolateChip_BattleDressUniform",
			"AFG_2008GreyChocolateChip_PulloverUniform",
			"AFG_2008GreyChocolateChip_ReconUniform",
			"AFG_2008GreyChocolateChip_FieldUniform",
			"AFG_2008GreyChocolateChip_FieldUniform_SS",
			"AFG_2008GreyChocolateChip_TacticalUniform",
			"AFG_2008GreyChocolateChip_TacticalUniform_SS",
			"AFG_2008GreyChocolateChip_TacticalUniform_TS",
			"AFG_2009APPFDigital_BattleDressUniform",
			"AFG_2009APPFDigital_PulloverUniform",
			"AFG_2009APPFDigital_ReconUniform",
			"AFG_2009APPFDigital_FieldUniform",
			"AFG_2009APPFDigital_FieldUniform_SS",
			"AFG_2009APPFDigital_TacticalUniform",
			"AFG_2009APPFDigital_TacticalUniform_SS",
			"AFG_2009APPFDigital_TacticalUniform_TS",
			"AFG_2009Spec4ceForest_BattleDressUniform",
			"AFG_2009Spec4ceForest_PulloverUniform",
			"AFG_2009Spec4ceForest_ReconUniform",
			"AFG_2009Spec4ceForest_FieldUniform",
			"AFG_2009Spec4ceForest_FieldUniform_SS",
			"AFG_2009Spec4ceForest_TacticalUniform",
			"AFG_2009Spec4ceForest_TacticalUniform_SS",
			"AFG_2009Spec4ceForest_TacticalUniform_TS",
			"AFG_2009Spec4ceSierra_BattleDressUniform",
			"AFG_2009Spec4ceSierra_PulloverUniform",
			"AFG_2009Spec4ceSierra_ReconUniform",
			"AFG_2009Spec4ceSierra_FieldUniform",
			"AFG_2009Spec4ceSierra_FieldUniform_SS",
			"AFG_2009Spec4ceSierra_TacticalUniform",
			"AFG_2009Spec4ceSierra_TacticalUniform_SS",
			"AFG_2009Spec4ceSierra_TacticalUniform_TS",
			"AFG_2012GhostexKilo1_BattleDressUniform",
			"AFG_2012GhostexKilo1_PulloverUniform",
			"AFG_2012GhostexKilo1_ReconUniform",
			"AFG_2012GhostexKilo1_FieldUniform",
			"AFG_2012GhostexKilo1_FieldUniform_SS",
			"AFG_2012GhostexKilo1_TacticalUniform",
			"AFG_2012GhostexKilo1_TacticalUniform_SS",
			"AFG_2012GhostexKilo1_TacticalUniform_TS"
		};
		weapons[] = {
			"AFG_1980DuckHunter_BattleDressUniform",
			"AFG_1980DuckHunter_PulloverUniform",
			"AFG_1980DuckHunter_ReconUniform",
			"AFG_1980DuckHunter_FieldUniform",
			"AFG_1980DuckHunter_FieldUniform_SS",
			"AFG_1980DuckHunter_TacticalUniform",
			"AFG_1980DuckHunter_TacticalUniform_SS",
			"AFG_1980DuckHunter_TacticalUniform_TS",
			"AFG_1990DuckHunter_BattleDressUniform",
			"AFG_1990DuckHunter_PulloverUniform",
			"AFG_1990DuckHunter_ReconUniform",
			"AFG_1990DuckHunter_FieldUniform",
			"AFG_1990DuckHunter_FieldUniform_SS",
			"AFG_1990DuckHunter_TacticalUniform",
			"AFG_1990DuckHunter_TacticalUniform_SS",
			"AFG_1990DuckHunter_TacticalUniform_TS",
			"AFG_1996DPM_BattleDressUniform",
			"AFG_1996DPM_PulloverUniform",
			"AFG_1996DPM_ReconUniform",
			"AFG_1996DPM_FieldUniform",
			"AFG_1996DPM_FieldUniform_SS",
			"AFG_1996DPM_TacticalUniform",
			"AFG_1996DPM_TacticalUniform_SS",
			"AFG_1996DPM_TacticalUniform_TS",
			"AFG_1996DuckHunter_BattleDressUniform",
			"AFG_1996DuckHunter_PulloverUniform",
			"AFG_1996DuckHunter_ReconUniform",
			"AFG_1996DuckHunter_FieldUniform",
			"AFG_1996DuckHunter_FieldUniform_SS",
			"AFG_1996DuckHunter_TacticalUniform",
			"AFG_1996DuckHunter_TacticalUniform_SS",
			"AFG_1996DuckHunter_TacticalUniform_TS",
			"AFG_1996Leaf_BattleDressUniform",
			"AFG_1996Leaf_PulloverUniform",
			"AFG_1996Leaf_ReconUniform",
			"AFG_1996Leaf_FieldUniform",
			"AFG_1996Leaf_FieldUniform_SS",
			"AFG_1996Leaf_TacticalUniform",
			"AFG_1996Leaf_TacticalUniform_SS",
			"AFG_1996Leaf_TacticalUniform_TS",
			"AFG_1996Woodland_BattleDressUniform",
			"AFG_1996Woodland_PulloverUniform",
			"AFG_1996Woodland_ReconUniform",
			"AFG_1996Woodland_FieldUniform",
			"AFG_1996Woodland_FieldUniform_SS",
			"AFG_1996Woodland_TacticalUniform",
			"AFG_1996Woodland_TacticalUniform_SS",
			"AFG_1996Woodland_TacticalUniform_TS",
			"AFG_2001Lizard_BattleDressUniform",
			"AFG_2001Lizard_PulloverUniform",
			"AFG_2001Lizard_ReconUniform",
			"AFG_2001Lizard_FieldUniform",
			"AFG_2001Lizard_FieldUniform_SS",
			"AFG_2001Lizard_TacticalUniform",
			"AFG_2001Lizard_TacticalUniform_SS",
			"AFG_2001Lizard_TacticalUniform_TS",
			"AFG_2002FourColorWoodland_BattleDressUniform",
			"AFG_2002FourColorWoodland_PulloverUniform",
			"AFG_2002FourColorWoodland_ReconUniform",
			"AFG_2002FourColorWoodland_FieldUniform",
			"AFG_2002FourColorWoodland_FieldUniform_SS",
			"AFG_2002FourColorWoodland_TacticalUniform",
			"AFG_2002FourColorWoodland_TacticalUniform_SS",
			"AFG_2002FourColorWoodland_TacticalUniform_TS",
			"AFG_2002Woodland_BattleDressUniform",
			"AFG_2002Woodland_PulloverUniform",
			"AFG_2002Woodland_ReconUniform",
			"AFG_2002Woodland_FieldUniform",
			"AFG_2002Woodland_FieldUniform_SS",
			"AFG_2002Woodland_TacticalUniform",
			"AFG_2002Woodland_TacticalUniform_SS",
			"AFG_2002Woodland_TacticalUniform_TS",
			"AFG_2008GreyChocolateChip_BattleDressUniform",
			"AFG_2008GreyChocolateChip_PulloverUniform",
			"AFG_2008GreyChocolateChip_ReconUniform",
			"AFG_2008GreyChocolateChip_FieldUniform",
			"AFG_2008GreyChocolateChip_FieldUniform_SS",
			"AFG_2008GreyChocolateChip_TacticalUniform",
			"AFG_2008GreyChocolateChip_TacticalUniform_SS",
			"AFG_2008GreyChocolateChip_TacticalUniform_TS",
			"AFG_2009APPFDigital_BattleDressUniform",
			"AFG_2009APPFDigital_PulloverUniform",
			"AFG_2009APPFDigital_ReconUniform",
			"AFG_2009APPFDigital_FieldUniform",
			"AFG_2009APPFDigital_FieldUniform_SS",
			"AFG_2009APPFDigital_TacticalUniform",
			"AFG_2009APPFDigital_TacticalUniform_SS",
			"AFG_2009APPFDigital_TacticalUniform_TS",
			"AFG_2009Spec4ceForest_BattleDressUniform",
			"AFG_2009Spec4ceForest_PulloverUniform",
			"AFG_2009Spec4ceForest_ReconUniform",
			"AFG_2009Spec4ceForest_FieldUniform",
			"AFG_2009Spec4ceForest_FieldUniform_SS",
			"AFG_2009Spec4ceForest_TacticalUniform",
			"AFG_2009Spec4ceForest_TacticalUniform_SS",
			"AFG_2009Spec4ceForest_TacticalUniform_TS",
			"AFG_2009Spec4ceSierra_BattleDressUniform",
			"AFG_2009Spec4ceSierra_PulloverUniform",
			"AFG_2009Spec4ceSierra_ReconUniform",
			"AFG_2009Spec4ceSierra_FieldUniform",
			"AFG_2009Spec4ceSierra_FieldUniform_SS",
			"AFG_2009Spec4ceSierra_TacticalUniform",
			"AFG_2009Spec4ceSierra_TacticalUniform_SS",
			"AFG_2009Spec4ceSierra_TacticalUniform_TS",
			"AFG_2012GhostexKilo1_BattleDressUniform",
			"AFG_2012GhostexKilo1_PulloverUniform",
			"AFG_2012GhostexKilo1_ReconUniform",
			"AFG_2012GhostexKilo1_FieldUniform",
			"AFG_2012GhostexKilo1_FieldUniform_SS",
			"AFG_2012GhostexKilo1_TacticalUniform",
			"AFG_2012GhostexKilo1_TacticalUniform_SS",
			"AFG_2012GhostexKilo1_TacticalUniform_TS",
			"AFG_Beret_ArmyGreen",
			"AFG_Beret_CommandoRed"
		};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Characters_F"};
	};
};

#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
