//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 182.144647 on Stable branch
// Generated with ALiVE version 1.6.1.1804271
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class CFP_O_CFRebels {
            name = "Central African Rebels";

            class Infantry {
                name = "Infantry";

                class cfp_o_cfrebels_infantry_sentry {
                    name = "Sentry";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Militiaman_01";
                    };
                };

                class cfp_o_cfrebels_infantry_sentry_gl {
                    name = "Sentry (GL)";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Grenadier_01";
                    };
                };

                class cfp_o_cfrebels_infantry_fireteam {
                    name = "Fireteam";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_RPG_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                };

                class cfp_o_cfrebels_infantry_assault_team {
                    name = "Assault Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Militiaman_01";
                    };
                };

                class cfp_o_cfrebels_infantry_fireteam_pkm {
                    name = "Fireteam (PKM)";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Machinegunner_PKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                };

                class cfp_o_cfrebels_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Surgeon_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Sharpshooter_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_RPG_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Grenadier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class cfp_o_cfrebels_specops_ex_military_sentry {
                    name = "Ex-Military Sentry";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Ex_FACA_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Ex_FACA_Rifleman_01";
                    };
                };

                class cfp_o_cfrebels_specops_ex_military_fireteam {
                    name = "Ex-Military Fireteam";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Ex_FACA_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Ex_FACA_Autorifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Sharpshooter_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Ex_FACA_Rifleman_01";
                    };
                };

                class cfp_o_cfrebels_specops_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Sharpshooter_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class cfp_o_cfrebels_motorized_light_technicals {
                    name = "Light Technicals";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Hilux_01";
                    };
                    class Unit1 {
                        position[] = {5,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Hilux_DShKM_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_RPG_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Grenadier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                };

                class cfp_o_cfrebels_motorized_heavy_technicals {
                    name = "Heavy Technicals";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Offroad_50_Cal_01";
                    };
                    class Unit1 {
                        position[] = {5,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Offroad_SPG_9_01";
                    };
                };

                class cfp_o_cfrebels_motorized_heavy_technicals2 {
                    name = "Heavy Technicals 2";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Hilux_ZU_23_01";
                    };
                    class Unit1 {
                        position[] = {5,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Hilux_SPG_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_RPG_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                };

                class cfp_o_cfrebels_motorized_squad {
                    name = "Motorized Squad";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Truck_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Surgeon_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_RPG_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Sharpshooter_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Grenadier_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Rifleman_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

                class cfp_o_cfrebels_support_medical_team {
                    name = "Medical Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Surgeon_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Militiaman_01";
                    };
                };

                class cfp_o_cfrebels_support_demo_team {
                    name = "Demo Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Autorifleman_RPK_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Demo_Specialist_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Militiaman_01";
                    };
                };

                class cfp_o_cfrebels_support_sharpshooter_team {
                    name = "Sharpshooter Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Machinegunner_PKM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Sharpshooter_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Militiaman_01";
                    };
                };

                class cfp_o_cfrebels_support_command_team {
                    name = "Command Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Commander_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Surgeon_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Ex_FACA_Autorifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Ex_FACA_Rifleman_01";
                    };
                };

                class cfp_o_cfrebels_support_mortar_team {
                    name = "Mortar Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Gunner_Mortar_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Assistant_Gunner_Mortar_01";
                    };
                };

                class cfp_o_cfrebels_support_hmg_team {
                    name = "HMG Team";
                    side = 0;
                    faction = "CFP_O_CFRebels";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Gunner_HMG_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_CFRebels_Assistant_Gunner_HMG_01";
                    };
                };

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};