class CfgPatches {
    class CFP_I_WAGNER {
        units[] = {
            "CFP_I_WAGNER_Contractor_2_DESERT_01",
            "CFP_I_WAGNER_Contractor_1_DESERT_01",
            "CFP_I_WAGNER_Marksman_DESERT_01",
            "CFP_I_WAGNER_Field_Medic_DESERT_01",
            "CFP_I_WAGNER_Field_Specialist_RPK_DESERT_01",
            "CFP_I_WAGNER_Field_Specialist_PKM_DESERT_01",
            "CFP_I_WAGNER_Field_Specialist_RPG_18_DESERT_01",
            "CFP_I_WAGNER_Field_Technician_DESERT_01",
            "CFP_I_WAGNER_Bodyguard_1_DESERT_01",
            "CFP_I_WAGNER_Bodyguard_2_DESERT_01",
            "CFP_I_WAGNER_Security_Contractor_AKMN_DESERT_01",
            "CFP_I_WAGNER_Security_Contractor_AK74_GL_DESERT_01",
            "CFP_I_WAGNER_Security_Contractor_SVD_DESERT_01",
            "CFP_I_WAGNER_Tactical_Driver_DESERT_01",
            "CFP_I_WAGNER_Tactical_Pilot_DESERT_01",
            "CFP_I_WAGNER_Tactical_Specialist_Igla_DESERT_01",
            "CFP_I_WAGNER_Team_Coordinator_DESERT_01",
            "CFP_I_WAGNER_BTR_80_DESERT_01",
            "CFP_I_WAGNER_BMP_2_DESERT_01",
            "CFP_I_WAGNER_Assault_Boat_DESERT_01",
            "CFP_I_WAGNER_Quad_Bike_DESERT_01",
            "CFP_I_WAGNER_Mk2_Light_Strike_Vehicle_DESERT_01",
            "CFP_I_WAGNER_Ural_DESERT_01",
            "CFP_I_WAGNER_Ural_Refuel_DESERT_01",
            "CFP_I_WAGNER_Ural_Repair_DESERT",
            "CFP_I_WAGNER_Ural_Ammo_DESERT_01",
            "CFP_I_WAGNER_UAZ_Medevac_DESERT_01",
            "CFP_I_WAGNER_UAZ_Open_DESERT_01",
            "CFP_I_WAGNER_UAZ_DESERT_01",
            "CFP_I_WAGNER_Van_Transport_DESERT_01",
            "CFP_I_WAGNER_Hilux_DESERT_01",
            "CFP_I_WAGNER_Hilux_DShKM_DESERT_01",
            "CFP_I_WAGNER_Hilux_SPG_DESERT_01",
            "CFP_I_WAGNER_Hilux_Igla_DESERT_01",
            "CFP_I_WAGNER_Hilux_Metis_DESERT_01",
            "CFP_I_WAGNER_MT_LB_LV_DESERT_01",
            "CFP_I_WAGNER_Pchela_1T_DESERT_01",
            "CFP_I_WAGNER_Mi24_D_DESERT_01",
            "CFP_I_WAGNER_Mi8_DESERT_01",
            "CFP_I_WAGNER_Ka60_DESERT_01",
            "CFP_I_WAGNER_ZU_23_DESERT_01",
            "CFP_I_WAGNER_SPG_9_DESERT_01",
            "CFP_I_WAGNER_Mortar_DESERT_01",
            "CFP_I_WAGNER_DShKM_DESERT_01",
            "CFP_I_WAGNER_DShKM_Low_DESERT_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "CUP_Creatures_Military_Russia",
            "A3_Characters_F",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USArmy",
            "CUP_Creatures_Military_USMC",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "A3_Data_F",
            "A3_Data_F_Curator"
        };
        author = "Drew";
        authors[] = {"Drew"};
    };
};
