class CfgPatches {
    class ADDON {
        units[] = {
            "CUP_B_T810_Armed_CZ_WDL",
            "CUP_B_T810_Unarmed_CZ_WDL",
            "CUP_B_T810_Refuel_CZ_WDL",
            "CUP_B_T810_Reammo_CZ_WDL",
            "CUP_B_T810_Repair_CZ_WDL",
            "CUP_B_BMP2_CZ_DES",
            "CUP_B_BMP_HQ_CZ_Des",
            "CUP_B_CZ_Soldier_805_WDL",
            "CUP_B_CZ_Soldier_805_GL_WDL",
            "CUP_B_CZ_Crew_WDL",
            "CUP_B_CZ_Soldier_SL_WDL",
            "CUP_B_CZ_Medic_WDL",
            "CUP_B_CZ_Soldier_MG_WDL",
            "CUP_B_CZ_Soldier_AR_WDL",
            "CUP_B_CZ_Officer_WDL",
            "CUP_B_CZ_Pilot_WDL",
            "CUP_B_CZ_Soldier_WDL",
            "CUP_B_CZ_SpecOps_WDL",
            "CUP_B_CZ_SpecOps_Recon_WDL",
            "CUP_B_CZ_SpecOps_TL_WDL",
            "CUP_B_CZ_SpecOps_Scout_WDL",
            "CUP_B_CZ_SpecOps_MG_WDL",
            "CUP_B_CZ_SpecOps_Exp_WDL",
            "CUP_B_CZ_Soldier_AT_WDL",
            "CUP_B_CZ_Soldier_RPG_WDL",
            "CUP_B_CZ_Engineer_WDL",
            "CUP_B_CZ_Sniper_WDL",
            "CUP_B_CZ_Soldier_Light_WDL",
            "CUP_B_CZ_Soldier_ARPG_WDL",
            "CUP_B_CZ_Soldier_Marksman_WDL",
            "CUP_B_BRDM2_CZ",
            "CUP_B_BRDM2_HQ_CZ",
            "CUP_B_Dingo_CZ_Wdl",
            "CUP_B_Dingo_GL_CZ_Wdl",
            "CUP_B_BMP2_CZ",
            "CUP_B_BMP_HQ_CZ",
            "CUP_B_BMP2_AMB_CZ",
            "CUP_B_BMP2_AMB_CZ_Des",
            "CUP_B_T72_CZ",
            "CUP_B_LR_Transport_CZ_W",
            "CUP_B_LR_MG_CZ_W",
            "CUP_B_LR_Ambulance_CZ_W",
            "CUP_B_LR_Special_CZ_W",
            "CUP_B_UAZ_Unarmed_ACR",
            "CUP_B_UAZ_Open_ACR",
            "CUP_B_UAZ_MG_ACR",
            "CUP_B_UAZ_AGS30_ACR",
            "CUP_B_UAZ_SPG9_ACR",
            "CUP_B_UAZ_METIS_ACR",
            "CUP_B_CZ_SpecOps_GL_WDL",
            "CFP_B_CZARMY_Mi_171Sh_Rockets_WDL_01",
            "CFP_B_CZARMY_Mi_171Sh_Unarmed_WDL_01",
            "CFP_B_CZARMY_Mi_35_Dark_WDL_01",
            "CFP_B_CZARMY_Mi_35_Tiger_WDL_01",
            "CFP_B_CZARMY_Mi_35_Ram_WDL_01",
            "CFP_B_CZARMY_Podnos_2B14_WDL_01",
            "CFP_B_CZARMY_Mi_35_WDL_01",
            "CFP_B_CZARMY_L39ZA_WDL_01",
            "CFP_B_CZARMY_AGS_30_WDL_01",
            "CFP_B_CZARMY_HMMWV_Ambulance_WDL_01",
            "CFP_B_CZARMY_DShKM_WDL_01",
            "CFP_B_CZARMY_HMMWV_M1151_M2_WDL_01",
            "CFP_B_CZARMY_HMMWV_M1114_DSHKM_WDL_01",
            "CFP_B_CZARMY_HMMWV_M1114_AGS_WDL_01",
            "CFP_B_CZARMY_RBS_70_WDL_01",
            "CUP_B_CZ_Soldier_AMG_WDL",
            "CUP_B_CZ_ExplosiveSpecialist_WDL",
            "CUP_B_CZ_Spotter_WDL",
            "CUP_B_CZ_Soldier_backpack_WDL"
        };
        weapons[] = {};
        requiredAddons[] = {
            "cfp_main",
            "CUP_WheeledVehicles_T810",
            "CUP_WheeledVehicles_HMMWV",
            "CUP_TrackedVehicles_BMP",
            "CUP_WheeledVehicles_LR",
            "CUP_Creatures_Military_ACR",
            "CUP_Weapons_StaticWeapons",
            "CUP_WheeledVehicles_BRDM2",
            "CUP_WheeledVehicles_Dingo",
            "CUP_TrackedVehicles_T72",
            "cfp_vehicles",
            "CUP_WheeledVehicles_UAZ",
            "CUP_AirVehicles_L39",
            "CUP_AirVehicles_Mi24",
            "CUP_AirVehicles_Mi8"
        };
        author = MODULE_AUTHOR;
        authors[] = {"CUP", "Tupolov"};
        requiredVersion = REQUIRED_VERSION;
        VERSION_CONFIG;
    };
};

