//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 182.144647 on Stable branch
// Generated with ALiVE version 1.6.1.1804271
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class INDEP {

        class CFP_I_SDMilitia {
            name = "Rapid Support Forces and Janjaweed";

            class Infantry {
                name = "Infantry";

                class CFP_I_SDMilitia_infantry_squad {
                    name = "Squad";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_14";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_06";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_05";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_03";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_03";
                    };
                };

                class CFP_I_SDMilitia_infantry_hmg_team {
                    name = "HMG Team";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_07";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_09";
                    };
                };

                class CFP_I_SDMilitia_infantry_hmg_team_low {
                    name = "HMG Team (Low)";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_08";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_09";
                    };
                };

                class CFP_I_SDMilitia_infantry_mortar_crew {
                    name = "Mortar Crew";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mortar.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_10";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_11";
                    };
                };

                class CFP_I_SDMilitia_infantry_at_team {
                    name = "AT Team";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_12";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_13";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                };

                class CFP_I_SDMilitia_infantry_militia {
                    name = "Militia";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_18";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_19";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_16";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_19";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_16";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                };

                class CFP_I_SDMilitia_infantry_militia_snipers {
                    name = "Militia Snipers";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_17";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_17";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class CFP_I_SDMilitia_motorized_aa_patrol {
                    name = "AA Patrol";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_antiair.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Ural_ZU_23_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_motorized_patrol_offroad {
                    name = "Patrol (Offroad)";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Offroad_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_motorized_patrol_pickup {
                    name = "Patrol (Pickup)";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_05";
                    };
                };

                class CFP_I_SDMilitia_motorized_patrol_pickup_pk {
                    name = "Patrol (Pickup/PK)";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_PK_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_motorized_patrol_hmg {
                    name = "Patrol (HMG)";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_UAZ_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_motorized_patrol_at {
                    name = "Patrol (AT)";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Land_Rover_SPG_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                };

                class CFP_I_SDMilitia_motorized_motorized_squad {
                    name = "Motorized Squad";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Land_Rover_01";
                    };
                    class Unit1 {
                        position[] = {5,-8,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_PK_01";
                    };
                    class Unit2 {
                        position[] = {-5,-8,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_14";
                    };
                    class Unit3 {
                        position[] = {10,-13,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_06";
                    };
                    class Unit4 {
                        position[] = {-10,-13,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit5 {
                        position[] = {15,-18,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-18,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit7 {
                        position[] = {20,-23,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit8 {
                        position[] = {-20,-23,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit9 {
                        position[] = {25,-28,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_05";
                    };
                    class Unit10 {
                        position[] = {-25,-28,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_05";
                    };
                    class Unit11 {
                        position[] = {30,-33,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_motorized_convoy {
                    name = "Convoy";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_UAZ_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-8,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_PK_01";
                    };
                    class Unit2 {
                        position[] = {-5,-8,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_PK_01";
                    };
                    class Unit3 {
                        position[] = {11,-16,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Truck_01";
                    };
                    class Unit4 {
                        position[] = {-11,-16,0};
                        rank = "LIEUTENANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_14";
                    };
                    class Unit5 {
                        position[] = {16,-21,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_06";
                    };
                    class Unit6 {
                        position[] = {-16,-21,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit7 {
                        position[] = {21,-26,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit8 {
                        position[] = {-21,-26,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit9 {
                        position[] = {26,-31,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit10 {
                        position[] = {-26,-31,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit11 {
                        position[] = {31,-36,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit12 {
                        position[] = {-31,-36,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit13 {
                        position[] = {36,-41,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_03";
                    };
                    class Unit14 {
                        position[] = {-36,-41,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_05";
                    };
                    class Unit15 {
                        position[] = {41,-46,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit16 {
                        position[] = {-41,-46,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit17 {
                        position[] = {46,-51,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit18 {
                        position[] = {-46,-51,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit19 {
                        position[] = {51,-56,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit20 {
                        position[] = {-51,-56,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_05";
                    };
                    class Unit21 {
                        position[] = {56,-61,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit22 {
                        position[] = {-56,-61,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_motorized_raiders {
                    name = "Raiders";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_PK_Militia_01";
                    };
                    class Unit1 {
                        position[] = {5,-8,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_Militia_01";
                    };
                    class Unit2 {
                        position[] = {-5,-8,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Offroad_Militia_01";
                    };
                    class Unit3 {
                        position[] = {10,-13,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_Militia_01";
                    };
                    class Unit4 {
                        position[] = {-10,-13,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Pickup_Militia_01";
                    };
                    class Unit5 {
                        position[] = {15,-18,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit6 {
                        position[] = {-15,-18,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_16";
                    };
                    class Unit7 {
                        position[] = {20,-23,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_16";
                    };
                    class Unit8 {
                        position[] = {-20,-23,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_18";
                    };
                    class Unit9 {
                        position[] = {25,-28,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_19";
                    };
                    class Unit10 {
                        position[] = {-25,-28,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit11 {
                        position[] = {30,-33,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit12 {
                        position[] = {-30,-33,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit13 {
                        position[] = {35,-38,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit14 {
                        position[] = {-35,-38,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit15 {
                        position[] = {40,-43,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_16";
                    };
                    class Unit16 {
                        position[] = {-40,-43,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_17";
                    };
                    class Unit17 {
                        position[] = {45,-48,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_18";
                    };
                    class Unit18 {
                        position[] = {-45,-48,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_19";
                    };
                    class Unit19 {
                        position[] = {50,-53,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_19";
                    };
                    class Unit20 {
                        position[] = {-50,-53,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_19";
                    };
                    class Unit21 {
                        position[] = {55,-58,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_19";
                    };
                    class Unit22 {
                        position[] = {-55,-58,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit23 {
                        position[] = {60,-63,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                    class Unit24 {
                        position[] = {-60,-63,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_15";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class CFP_I_SDMilitia_mechanized_armored_patrol {
                    name = "Armored Patrol";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Walid_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

                class CFP_I_SDMilitia_mechanized_armored_patrol_hmg {
                    name = "Armored Patrol (HMG)";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Walid_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class CFP_I_SDMilitia_armored_t55_patrol {
                    name = "T-55 Patrol";
                    side = 2;
                    faction = "CFP_I_SDMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_T55_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_04";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_02";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "CFP_I_SDMilitia_Soldier_03";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};
