//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 176.143187 on Stable branch
// Generated with ALiVE version 1.5.0.1711091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class CFP_O_SOREBEL {
        displayName = "Somali Rebels";
        side = 0;
        flag = "\x\cfp\addons\flags\Somalia\Somali_Pirates.paa";
        icon = "\x\cfp\addons\flags\Somalia\Somali_Pirates.paa";
        priority = 1;
    };
};