//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 188.145285 on Stable branch
// Generated with ALiVE version 1.8.3.1812041
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class CFP_O_IS {
            name = "Islamic State";

            class Infantry {
                name = "Infantry";

                class cfp_o_grp_is_sentry {
                    name = "Sentry";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\NATO\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_militaman";
                    };
                };

                class cfp_o_grp_is_inf_squad {
                    name = "Infantry Squad";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\NATO\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_squad_leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_grenadier";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_autorifleman";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_machinegunner";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_sniper";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_at";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

                class cfp_o_grp_is_wpn_squad {
                    name = "Weapons Squad";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\NATO\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_squad_leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_grenadier";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_machinegunner";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_autorifleman";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_medic";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_sniper";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_at";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_sapper";
                    };
                };

                class cfp_o_grp_is_inf_fire_team {
                    name = "Fire Team";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\NATO\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_squad_leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_machinegunner";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_sniper";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

                class cfp_o_grp_is_at_team {
                    name = "Anti-Armor Team";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\NATO\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_squad_leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_at";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_at";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_machinegunner";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

                class cfp_o_grp_is_hq_squad {
                    name = "HQ Squad";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\NATO\o_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "cfp_o_is_team_leader";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_squad_leader";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_grenadier";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_machinegunner";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_medic";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_sniper";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_at";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class cfp_o_is_infantry_dshkm_team {
                    name = "DShKM Team";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman_dshkm";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_Asst_Gunner_DSHKM";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

                class cfp_o_is_infantry_kord_team {
                    name = "KORD Team";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman_kord";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_Asst_Gunner_KORD";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

                class cfp_o_is_infantry_mortar_team {
                    name = "Mortar Team";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman_podnos";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_Asst_Gunner_Podnos";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman_podnos";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_Asst_Gunner_Podnos";
                    };
                };

                class cfp_o_is_infantry_metis_at_team {
                    name = "METIS AT Team";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman_metis";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_Asst_Gunner_METIS";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

                class cfp_o_is_infantry_spg_9team {
                    name = "SPG-9 Team";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman_spg9";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_Asst_Gunner_SPG";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_rifleman";
                    };
                };

            };

            class Motorized {
                name = "Motorized";

                class cfp_o_grp_is_offroad_mgs {
                    name = "IS Offroad MGs";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_offroad_M2";
                    };
                };

                class cfp_o_grp_is_offroad_patrol {
                    name = "IS Offroad Patrol";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_offroad_M2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_SPG_01";
                    };
                };

                class cfp_o_grp_is_lr_mgs {
                    name = "IS L.R. MGs";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_LR_M2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_LR_M2";
                    };
                };

                class cfp_o_grp_is_lr_light_support {
                    name = "IS L.R. Support";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_LR_M2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_LR_SPG9";
                    };
                };

                class cfp_o_grp_is_lr_heavy_support {
                    name = "IS L.R. Heavy Support";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_LR_M2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_LR_SPG9";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_LR_SPG9";
                    };
                };

                class cfp_o_grp_is_uaz_mgs {
                    name = "IS UAZ MGs";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_UAZ_MG";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_UAZ_MG";
                    };
                };

                class cfp_o_grp_is_uaz_light_support {
                    name = "IS UAZ Support";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_UAZ_MG";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_UAZ_AGS30";
                    };
                };

                class cfp_o_grp_is_uaz_heavy_support {
                    name = "IS UAZ Heavy Support";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_UAZ_MG";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_UAZ_AGS30";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_UAZ_SPG9";
                    };
                };

                class cfp_o_grp_is_mixed_technicals_1 {
                    name = "IS Mixed Technicals 1";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_SPG_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_Metis_01";
                    };
                };

                class cfp_o_grp_is_mixed_technicals_2 {
                    name = "IS Mixed Technicals 2";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_BTR60_Armored_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_AGS_30_01";
                    };
                };

                class cfp_o_grp_is_mixed_technicals_3 {
                    name = "IS Mixed Technicals 3";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_DShKM_Armored_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_SPG_Armored_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_Metis_Armored_01";
                    };
                };

                class cfp_o_grp_is_mixed_technicals_4 {
                    name = "IS Mixed Technicals 4";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_DShKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_Igla_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_ZU_23_01";
                    };
                };

                class cfp_o_grp_is_mixed_technicals_5 {
                    name = "IS Mixed Technicals 5";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_BMP1_Armored_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_BTR60_Armored_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized";

                class cfp_o_grp_is_bmp1 {
                    name = "IS BMP-1";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                };

                class cfp_o_grp_is_bmp1_section {
                    name = "IS BMP-1 Section";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                };

                class cfp_o_grp_is_bmp1_platoon {
                    name = "IS BMP-1 Platoon";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                };

                class cfp_o_grp_is_bmp1p {
                    name = "IS BMP-1P";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                };

                class cfp_o_grp_is_bmp1p_section {
                    name = "IS BMP-1P Section";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                };

                class cfp_o_grp_is_bmp1p_platoon {
                    name = "IS BMP-1P Platoon";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                };

                class cfp_o_grp_is_bmp2 {
                    name = "IS BMP-2";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                };

                class cfp_o_grp_is_bmp2_section {
                    name = "IS BMP-2 Section";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                };

                class cfp_o_grp_is_bmp2_platoon {
                    name = "IS BMP-2 Platoon";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                };

                class cfp_o_grp_is_bmps_mixed_1 {
                    name = "IS BMPs Mixed 1";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                };

                class cfp_o_grp_is_bmps_mixed_2 {
                    name = "IS BMPs Mixed 2";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                };

                class cfp_o_grp_is_bmps_mixed_3 {
                    name = "IS BMPs Mixed 3";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_mech_inf.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1P";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP1";
                    };
                };

            };

            class Armored {
                name = "Armored";

                class cfp_o_grp_is_t55 {
                    name = "IS T-55";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                };

                class cfp_o_grp_is_t55_section {
                    name = "IS T-55 Section";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                };

                class cfp_o_grp_is_t55_platoon {
                    name = "IS T-55 Platoon";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                };

                class cfp_o_grp_is_t72 {
                    name = "IS T-72";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                };

                class cfp_o_grp_is_t72_section {
                    name = "IS T-72 Section";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                };

                class cfp_o_grp_is_t72_platoon {
                    name = "IS T-72 Platoon";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                };

                class cfp_o_grp_is_mixed_armor_1 {
                    name = "IS Mixed Armor 1";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                };

                class cfp_o_grp_is_mixed_armor_2 {
                    name = "IS Mixed Armor 2";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                };

                class cfp_o_grp_is_mixed_armor_3 {
                    name = "IS Mixed Armor 3";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.3;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "cfp_o_is_T72";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_BMP2";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "cfp_o_is_T55";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class cfp_o_is_artillery_motorized_mlrs_hilux_battery {
                    name = "Motorized MLRS Hilux Battery";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_MLRS_01";
                    };
                };

                class cfp_o_is_artillery_motorized_mortar_hilux_battery {
                    name = "Motorized Mortar Hilux Battery";
                    side = 0;
                    faction = "CFP_O_IS";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "CFP_O_IS_Hilux_Podnos_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};