//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 188.145285 on Stable branch
// Generated with ALiVE version 1.8.3.1812041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class CFP_O_CHDKZ_Winter {
        displayName = "Chernarussian Movement of the Red Star [Winter]";
        side = 0;
        flag = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_chdkz_co.paa";
        icon = "CUP\BaseConfigs\CUP_BaseConfigs\Data\Flags\flag_chdkz_co.paa";
        priority = 4;
    };
};