//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 176.143187 on Stable branch
// Generated with ALiVE version 1.3.7.0000000
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class CUP_B_CZ {
        displayName = "Army of the Czech Rep. (Arid / Desert)";
    };
};