class CfgPatches {
    class ADDON {
        units[] = {
            "CUP_B_T810_Armed_CZ_DES",
            "CUP_B_T810_Unarmed_CZ_DES",
            "CUP_B_T810_Refuel_CZ_DES",
            "CUP_B_T810_Reammo_CZ_DES",
            "CUP_B_T810_Repair_CZ_DES",
            "CUP_B_HMMWV_M2_GPK_ACR",
            "CUP_B_HMMWV_DSHKM_GPK_ACR",
            "CUP_B_HMMWV_AGS_GPK_ACR",
            "CUP_B_LR_Special_Des_CZ_D",
            "CUP_B_CZ_Soldier_SL_DES",
            "CUP_B_CZ_Soldier_DES",
            "CUP_B_CZ_Soldier_Backpack_DES",
            "CUP_B_CZ_Medic_DES",
            "CUP_B_CZ_Soldier_AMG_DES",
            "CUP_B_CZ_Soldier_AT_DES",
            "CUP_B_CZ_Soldier_MG_DES",
            "CUP_B_CZ_Officer_DES",
            "CUP_B_CZ_Soldier_Light_DES",
            "CUP_B_CZ_Pilot_DES",
            "CUP_B_CZ_Sniper_DES",
            "CUP_B_CZ_SpecOps_Scout_DES",
            "CUP_B_CZ_SpecOps_Recon_DES",
            "CUP_B_CZ_ExplosiveSpecialist_DES",
            "CUP_B_CZ_SpecOps_MG_DES",
            "CUP_B_CZ_SpecOps_DES",
            "CUP_B_CZ_SpecOps_TL_DES",
            "CUP_B_CZ_SpecOps_GL_DES",
            "CUP_B_CZ_Soldier_805_DES",
            "CUP_B_CZ_Soldier_805_GL_DES",
            "CUP_B_CZ_Crew_DES",
            "CUP_B_CZ_Soldier_AR_DES",
            "CUP_B_CZ_SpecOps_Exp_DES",
            "CUP_B_CZ_Soldier_RPG_DES",
            "CUP_B_CZ_Engineer_DES",
            "CUP_B_CZ_Spotter_DES",
            "CUP_B_CZ_Soldier_ARPG_DES",
            "CUP_B_CZ_Soldier_Marksman_DES",
            "CUP_B_RBS70_ACR",
            "CUP_B_DSHKM_ACR",
            "CUP_B_AGS_ACR",
            "CUP_B_2b14_82mm_ACR",
            "CUP_B_BRDM2_CZ_Des",
            "CUP_B_BRDM2_HQ_CZ_Des",
            "CUP_B_Dingo_CZ_Des",
            "CUP_B_Dingo_GL_CZ_Des",
            "CUP_B_HMMWV_Ambulance_ACR",
            "CUP_B_LR_Transport_CZ_D",
            "CUP_B_LR_Ambulance_CZ_D",
            "CUP_B_L39_CZ",
            "CUP_B_Mi35_Dynamic_CZ",
            "CUP_B_Mi35_Dynamic_CZ_Des",
            "CUP_B_Mi35_Dynamic_CZ_Ram",
            "CUP_B_Mi35_Dynamic_CZ_Tiger",
            "CUP_B_Mi35_Dynamic_CZ_Dark",
            "CUP_B_Mi171Sh_ACR",
            "CUP_B_Mi171Sh_Unarmed_ACR",
            "CUP_B_LR_MG_CZ_D",
            "CFP_B_T72M4CZ_01",
            "CFP_B_UAZ_Metis_01",
            "CFP_B_UAZ_01",
            "CFP_B_UAZ_Open_01",
            "CFP_B_UAZ_DShKM_01",
            "CFP_B_UAZ_AGS_30_01",
            "CFP_B_UAZ_SPG_01"
        };
        weapons[] = {};
        requiredAddons[] = {
            "CUP_WheeledVehicles_T810",
            "CUP_WheeledVehicles_HMMWV",
            "CUP_TrackedVehicles_BMP",
            "CUP_WheeledVehicles_LR",
            "CUP_Creatures_Military_ACR",
            "CUP_Weapons_StaticWeapons",
            "CUP_WheeledVehicles_BRDM2",
            "CUP_WheeledVehicles_Dingo",
            "CUP_TrackedVehicles_T72",
            "cfp_vehicles",
            "CUP_WheeledVehicles_UAZ",
            "CUP_AirVehicles_L39",
            "CUP_AirVehicles_Mi24",
            "CUP_AirVehicles_Mi8",
            "CFP_B_CZARMY_WDL"
        };
      author = MODULE_AUTHOR;
      authors[] = {"CUP", "Tupolov"};
      requiredVersion = REQUIRED_VERSION;
      VERSION_CONFIG;
    };
};

